"""Git-bisect wrapper for finding which XS commit broke a doctrine probe.

Automates the outer ``git bisect`` loop (start, generate test script) for AoE3
AI doctrine regression hunts.  The inner test — deploying and running the game
to observe probe values — requires human interaction at each step, because the
game cannot be launched non-interactively until ``exhibition_runner`` supports
autonomous mode.

The generated test script (``BISECT_SCRIPT_NAME``) is a bash script that:
1. Deploys the current checkout via ``tools/deploy_to_mod.py``.
2. Prints instructions for the operator to run the game and report the result.
3. Exits with code 125 (git bisect SKIP) so the operator can mark manually.

Usage::

    python3 -m tools.aoe3_harness.bisect \\
        --probe wall.closure \\
        --civ ANWFrench \\
        --target 0.6 \\
        --good <good_sha> \\
        --bad <bad_sha>

Or via the CLI::

    python3 -m tools.aoe3_harness.cli bisect \\
        --probe wall.closure --civ ANWFrench --target 0.6 \\
        --good abc1234 --bad def5678

Design note:
    Full automation (``git bisect run``) is intentionally not wired up until
    ``exhibition_runner`` can be triggered non-interactively.  All git plumbing
    is complete so bisection can begin immediately with minimal manual overhead.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import textwrap
from pathlib import Path
from typing import Optional

# Path (relative to repo root) of the generated bisect test script.
BISECT_SCRIPT_NAME: str = ".git/bisect_test_anw.sh"


def _run_git(
    args: list[str],
    cwd: Path,
    check: bool = True,
) -> subprocess.CompletedProcess:
    """Run a git subcommand and return the CompletedProcess result.

    Args:
        args:  Arguments after ``git``, e.g. ``["bisect", "start"]``.
        cwd:   Working directory (must be the repo root).
        check: If ``True``, raise :class:`subprocess.CalledProcessError` on
               non-zero exit.

    Returns:
        :class:`subprocess.CompletedProcess` with captured stdout/stderr.
    """
    return subprocess.run(
        ["git"] + args,
        cwd=str(cwd),
        capture_output=True,
        text=True,
        check=check,
    )


def _write_bisect_test_script(
    repo_root: Path,
    probe: str,
    civ: str,
    target: float,
) -> Path:
    """Write a bash test script suitable for ``git bisect run``.

    The script deploys the current checkout via ``deploy_to_mod.py`` and then
    prints manual test instructions.  It exits with code 125 (SKIP) so git
    bisect does not advance automatically — the operator marks each commit
    manually with ``git bisect good`` / ``git bisect bad``.

    Args:
        repo_root: Absolute path to the repository root.
        probe:     Name of the probe to test, e.g. ``"wall.closure"``.
        civ:       Civ token, e.g. ``"ANWFrench"``.
        target:    Minimum acceptable probe value, e.g. ``0.6``.

    Returns:
        Absolute path to the written test script.
    """
    script_path = repo_root / BISECT_SCRIPT_NAME
    deploy_script = repo_root / "tools" / "deploy_to_mod.py"

    script_content = textwrap.dedent(f"""\
        #!/usr/bin/env bash
        # ANW git-bisect test script
        # Generated by tools/aoe3_harness/bisect.py — do not edit manually.
        # Re-generate by re-running bisect.py with the same arguments.
        #
        # Exit codes (git-bisect-run convention):
        #   0   GOOD — probe passes at this commit
        #   1   BAD  — probe fails at this commit
        #   125 SKIP — cannot test this commit (deploy failed, or manual step needed)
        set -euo pipefail

        REPO_ROOT="{repo_root}"
        PROBE="{probe}"
        CIV="{civ}"
        TARGET="{target}"

        echo "==================================================="
        echo "  ANW Bisect Test"
        echo "  Probe:  $PROBE"
        echo "  Civ:    $CIV"
        echo "  Target: >= $TARGET"
        echo "  Commit: $(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)"
        echo "==================================================="

        # Step 1: Deploy this checkout to the mod directory
        echo "[bisect] Deploying mod files..."
        if ! python3 "{deploy_script}"; then
            echo "[bisect] Deploy FAILED — skipping commit (exit 125)"
            exit 125
        fi
        echo "[bisect] Deploy OK"

        # Step 2: Live-game test required — autonomous mode not yet available.
        # Mark this commit manually after running exhibition_runner.
        echo ""
        echo "+---------------------------------------------------------+"
        echo "|  MANUAL TEST REQUIRED                                   |"
        echo "|                                                         |"
        echo "|  1. Launch AoE3 with:                                   |"
        echo "|       WINEDLLOVERRIDES=anw_hook=n,b                     |"
        echo "|  2. Run exhibition_runner for civ: $CIV"
        echo "|  3. Check probe '$PROBE' >= $TARGET"
        echo "|  4. Mark result after the game exits:                   |"
        echo "|       git bisect good   (probe >= $TARGET)         |"
        echo "|       git bisect bad    (probe <  $TARGET)         |"
        echo "|       git bisect skip   (game crashed / untestable)     |"
        echo "+---------------------------------------------------------+"
        echo ""
        echo "[bisect] Exiting 125 (SKIP) — awaiting manual mark."
        exit 125
    """)

    script_path.write_text(script_content, encoding="utf-8")
    script_path.chmod(0o755)
    return script_path


def run_bisect(
    repo_root: Path,
    probe: str,
    civ: str,
    target: float,
    good_sha: str,
    bad_sha: str,
) -> int:
    """Initialise a git bisect session and print operator instructions.

    Runs ``git bisect start <bad_sha> <good_sha>``, writes the test script,
    and explains the manual workflow.

    Args:
        repo_root: Absolute path to the repository root.
        probe:     Probe name to test, e.g. ``"wall.closure"``.
        civ:       Civ token, e.g. ``"ANWFrench"``.
        target:    Minimum acceptable probe value (float), e.g. ``0.6``.
        good_sha:  A known-good commit SHA (probe passes at this commit).
        bad_sha:   A known-bad commit SHA (probe fails at this commit).

    Returns:
        0 on success, 1 on git error.
    """
    print(f"\n[bisect] Starting git bisect")
    print(f"[bisect]   probe:  {probe}")
    print(f"[bisect]   civ:    {civ}")
    print(f"[bisect]   target: >= {target}")
    print(f"[bisect]   good:   {good_sha}")
    print(f"[bisect]   bad:    {bad_sha}")
    print()

    try:
        result = _run_git(["bisect", "start", bad_sha, good_sha], cwd=repo_root)
        if result.stdout.strip():
            print(result.stdout.strip())
        if result.stderr.strip():
            print(result.stderr.strip(), file=sys.stderr)
    except subprocess.CalledProcessError as exc:
        print(
            f"[bisect] ERROR: git bisect start failed:\n{exc.stderr}",
            file=sys.stderr,
        )
        return 1

    test_script = _write_bisect_test_script(repo_root, probe, civ, target)
    print(f"[bisect] Test script written: {test_script}")
    print()
    print("[bisect] To run semi-automated bisection (deploys only; game test is manual):")
    print(f"         git bisect run {test_script}")
    print()
    print("[bisect] To walk the bisect manually:")
    print("         git bisect good  — mark current commit as good")
    print("         git bisect bad   — mark current commit as bad")
    print("         git bisect log   — show bisect history")
    print("         git bisect reset — abandon bisect and return to HEAD")
    print()
    print("[bisect] NOTE: live game testing is required at each step.")
    print("[bisect] See README.md for exhibition_runner invocation instructions.")

    # Show current bisect state
    status = _run_git(["bisect", "log"], cwd=repo_root, check=False)
    if status.returncode == 0 and status.stdout.strip():
        print(f"\n[bisect] Current state:\n{status.stdout.strip()}")

    return 0


def main(argv: Optional[list[str]] = None) -> int:
    """CLI entry point for the git-bisect wrapper.

    Args:
        argv: Argument list (default: ``sys.argv[1:]``).

    Returns:
        Exit code: 0 on success, non-zero on error.
    """
    ap = argparse.ArgumentParser(
        prog="python3 -m tools.aoe3_harness.bisect",
        description=(
            "Git-bisect wrapper for ANW doctrine probe regression hunts. "
            "Sets up bisect and generates a test script; game testing is manual."
        ),
    )
    ap.add_argument("--probe",  required=True, help="probe name, e.g. wall.closure")
    ap.add_argument("--civ",    required=True, help="civ token, e.g. ANWFrench")
    ap.add_argument("--target", required=True, type=float,
                    help="minimum acceptable probe value, e.g. 0.6")
    ap.add_argument("--good",   required=True, help="known-good commit SHA")
    ap.add_argument("--bad",    required=True, help="known-bad commit SHA")

    args = ap.parse_args(argv)
    repo_root = Path(__file__).resolve().parents[2]

    return run_bisect(
        repo_root=repo_root,
        probe=args.probe,
        civ=args.civ,
        target=args.target,
        good_sha=args.good,
        bad_sha=args.bad,
    )


if __name__ == "__main__":
    sys.exit(main())
