// AUTO-GENERATED by tools/ai_design/wall_knob_calibration.py
// 62-civ × 14-knob calibration table.
// Edit the .py file and re-emit; do not hand-edit this XS file.
//
// Called from aiLoaderStandard.xs::preInit() AFTER initLeader<Name>()
// so per-civ knobs override any strategy defaults set in leader files.

void anwSetWallKnobsForCiv(void)
{
   // Resolve civ key — use kbGetCivName so we can distinguish
   // base civs from revolution-spawn civs (ANW*).
   string civKey = kbGetCivName(cMyCiv);

   if (civKey == "DEInca")
   {
      // DEInca: Tight terraced core, early stone, valley-mouth chokes secondary
      gANWWallStrategy             = 0;
      gANWWallRadius               = 14;
      gANWWallGateCount            = 2;
      gANWWallTierAge2Stone        = true;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 4;
      gANWWallSecondaryStrategy    = 1;
      gANWWallVillagerCount        = 8;
      gANWWallForwardBiasFraction  = 0.2;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 2;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "Germans")
   {
      // Germans: Prussian double-ring around drillyard, tower-dense, strict closure
      gANWWallStrategy             = 4;
      gANWWallRadius               = 14;
      gANWWallGateCount            = 3;
      gANWWallTierAge2Stone        = true;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 8;
      gANWWallSecondaryStrategy    = 0;
      gANWWallVillagerCount        = 7;
      gANWWallForwardBiasFraction  = 0.25;
      gANWWallOuterRingDelta       = 8;
      gANWWallEarlyOutpostCount    = 2;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "Ottomans")
   {
      // Ottomans: Janissary-engineer double ring, open gate count for trade, outer ring for siege absorption
      gANWWallStrategy             = 0;
      gANWWallRadius               = 20;
      gANWWallGateCount            = 4;
      gANWWallTierAge2Stone        = true;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 6;
      gANWWallSecondaryStrategy    = 4;
      gANWWallVillagerCount        = 8;
      gANWWallForwardBiasFraction  = 0.3;
      gANWWallOuterRingDelta       = 6;
      gANWWallEarlyOutpostCount    = 2;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "DEMaltese")
   {
      // DEMaltese: Order of St John siege doctrine, tower spam, double ring, coastal Coastal fallback
      gANWWallStrategy             = 0;
      gANWWallRadius               = 16;
      gANWWallGateCount            = 3;
      gANWWallTierAge2Stone        = true;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 8;
      gANWWallSecondaryStrategy    = 2;
      gANWWallVillagerCount        = 10;
      gANWWallForwardBiasFraction  = 0.15;
      gANWWallOuterRingDelta       = 6;
      gANWWallEarlyOutpostCount    = 1;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "Chinese")
   {
      // Chinese: Wall doctrine: long defensive spine with watchtowers, choke fallback for hills
      gANWWallStrategy             = 0;
      gANWWallRadius               = 18;
      gANWWallGateCount            = 3;
      gANWWallTierAge2Stone        = true;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 5;
      gANWWallSecondaryStrategy    = 1;
      gANWWallVillagerCount        = 7;
      gANWWallForwardBiasFraction  = 0.4;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 2;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "French")
   {
      // French: Vauban-style star fort, narrow gates, royal court depth
      gANWWallStrategy             = 0;
      gANWWallRadius               = 18;
      gANWWallGateCount            = 2;
      gANWWallTierAge2Stone        = true;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 7;
      gANWWallSecondaryStrategy    = 2;
      gANWWallVillagerCount        = 9;
      gANWWallForwardBiasFraction  = 0.2;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 2;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "Indians")
   {
      // Indians: Maratha hill-fort citadel, dense tower interleave, ghat-pass choke fallback
      gANWWallStrategy             = 0;
      gANWWallRadius               = 16;
      gANWWallGateCount            = 2;
      gANWWallTierAge2Stone        = true;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 7;
      gANWWallSecondaryStrategy    = 1;
      gANWWallVillagerCount        = 7;
      gANWWallForwardBiasFraction  = 0.35;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 2;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "DEEthiopians")
   {
      // DEEthiopians: Highland fortress with long sparse defensive lines, late stone-tier (resource-scarce)
      gANWWallStrategy             = 0;
      gANWWallRadius               = 20;
      gANWWallGateCount            = 3;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 4;
      gANWWallSecondaryStrategy    = 1;
      gANWWallVillagerCount        = 5;
      gANWWallForwardBiasFraction  = 0.4;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 3;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "XPAztec")
   {
      // XPAztec: Causeway/jungle choke walls, mostly War Hut substitution, late + sparse
      gANWWallStrategy             = 1;
      gANWWallRadius               = 10;
      gANWWallGateCount            = 2;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 3;
      gANWWallSecondaryStrategy    = 5;
      gANWWallVillagerCount        = 3;
      gANWWallForwardBiasFraction  = 0.75;
      gANWWallOuterRingDelta       = 0;
      gANWWallEarlyOutpostCount    = 4;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "British")
   {
      // British: Channel-defense coastal, dense towers facing land, gates open for trade
      gANWWallStrategy             = 2;
      gANWWallRadius               = 22;
      gANWWallGateCount            = 4;
      gANWWallTierAge2Stone        = true;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 6;
      gANWWallSecondaryStrategy    = 0;
      gANWWallVillagerCount        = 6;
      gANWWallForwardBiasFraction  = 0.2;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 2;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "Portuguese")
   {
      // Portuguese: Atlantic carrack-defense coastal, gates face inland trade, water is wide-open by design
      gANWWallStrategy             = 2;
      gANWWallRadius               = 22;
      gANWWallGateCount            = 4;
      gANWWallTierAge2Stone        = true;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 5;
      gANWWallSecondaryStrategy    = 0;
      gANWWallVillagerCount        = 6;
      gANWWallForwardBiasFraction  = 0.2;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 2;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "Dutch")
   {
      // Dutch: Dutch dyke-defense, narrow gates, tower-spam, urban barricade fallback in city core
      gANWWallStrategy             = 2;
      gANWWallRadius               = 18;
      gANWWallGateCount            = 3;
      gANWWallTierAge2Stone        = true;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 7;
      gANWWallSecondaryStrategy    = 4;
      gANWWallVillagerCount        = 7;
      gANWWallForwardBiasFraction  = 0.15;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 2;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "DEHausa")
   {
      // DEHausa: Hausa caravanserai frontier, palisade only, mobile fallback for jihad raids
      gANWWallStrategy             = 3;
      gANWWallRadius               = 18;
      gANWWallGateCount            = 5;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 3;
      gANWWallSecondaryStrategy    = 5;
      gANWWallVillagerCount        = 4;
      gANWWallForwardBiasFraction  = 0.55;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 4;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "Russians")
   {
      // Russians: Kremlin-style palisade-then-stone with sentinel towers on steppe frontier
      gANWWallStrategy             = 3;
      gANWWallRadius               = 22;
      gANWWallGateCount            = 4;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 4;
      gANWWallSecondaryStrategy    = 0;
      gANWWallVillagerCount        = 5;
      gANWWallForwardBiasFraction  = 0.45;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 4;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "DEItalians")
   {
      // DEItalians: Risorgimento city walls, Colonial trigger, tight ring with bell-tower observation
      gANWWallStrategy             = 4;
      gANWWallRadius               = 12;
      gANWWallGateCount            = 3;
      gANWWallTierAge2Stone        = true;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 5;
      gANWWallSecondaryStrategy    = 0;
      gANWWallVillagerCount        = 4;
      gANWWallForwardBiasFraction  = 0.15;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 1;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "DEMexicans")
   {
      // DEMexicans: Insurgente town barricade, palisade-tier (resource constraint), frontier fallback
      gANWWallStrategy             = 4;
      gANWWallRadius               = 11;
      gANWWallGateCount            = 3;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 4;
      gANWWallSecondaryStrategy    = 3;
      gANWWallVillagerCount        = 4;
      gANWWallForwardBiasFraction  = 0.2;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 2;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "DEAmericans")
   {
      // DEAmericans: Continental Army camp barricade, stone Colonial, frontier-palisade fallback in field
      gANWWallStrategy             = 4;
      gANWWallRadius               = 12;
      gANWWallGateCount            = 3;
      gANWWallTierAge2Stone        = true;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 5;
      gANWWallSecondaryStrategy    = 3;
      gANWWallVillagerCount        = 5;
      gANWWallForwardBiasFraction  = 0.2;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 2;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "XPIroquois")
   {
      // XPIroquois: Iroquois Confederacy — longhouse village, no perimeter walls, choke fallback at portages
      gANWWallStrategy             = 5;
      gANWWallRadius               = 0;
      gANWWallGateCount            = 0;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 5;
      gANWWallSegmentLength        = 0;
      gANWWallTowerInterleave      = 0;
      gANWWallSecondaryStrategy    = 1;
      gANWWallVillagerCount        = 0;
      gANWWallForwardBiasFraction  = 0.0;
      gANWWallOuterRingDelta       = 0;
      gANWWallEarlyOutpostCount    = 5;
      gANWWallRepairAggressiveness = 0;
      gANWWallClosurePctTarget     = 0;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "Japanese")
   {
      // Japanese: Tokugawa daimyō field army, no walls, urban barricade fallback at castle
      gANWWallStrategy             = 5;
      gANWWallRadius               = 0;
      gANWWallGateCount            = 0;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 5;
      gANWWallSegmentLength        = 0;
      gANWWallTowerInterleave      = 0;
      gANWWallSecondaryStrategy    = 4;
      gANWWallVillagerCount        = 0;
      gANWWallForwardBiasFraction  = 0.0;
      gANWWallOuterRingDelta       = 0;
      gANWWallEarlyOutpostCount    = 3;
      gANWWallRepairAggressiveness = 0;
      gANWWallClosurePctTarget     = 0;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "XPSioux")
   {
      // XPSioux: Plains horse warrior — pure mobile, outpost screen, frontier fallback
      gANWWallStrategy             = 5;
      gANWWallRadius               = 0;
      gANWWallGateCount            = 0;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 5;
      gANWWallSegmentLength        = 0;
      gANWWallTowerInterleave      = 0;
      gANWWallSecondaryStrategy    = 3;
      gANWWallVillagerCount        = 0;
      gANWWallForwardBiasFraction  = 0.0;
      gANWWallOuterRingDelta       = 0;
      gANWWallEarlyOutpostCount    = 5;
      gANWWallRepairAggressiveness = 0;
      gANWWallClosurePctTarget     = 0;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "Spanish")
   {
      // Spanish: Reconquista mobile column, coastal fallback (Iberian peninsula)
      gANWWallStrategy             = 5;
      gANWWallRadius               = 0;
      gANWWallGateCount            = 0;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 5;
      gANWWallSegmentLength        = 0;
      gANWWallTowerInterleave      = 0;
      gANWWallSecondaryStrategy    = 2;
      gANWWallVillagerCount        = 0;
      gANWWallForwardBiasFraction  = 0.0;
      gANWWallOuterRingDelta       = 0;
      gANWWallEarlyOutpostCount    = 3;
      gANWWallRepairAggressiveness = 0;
      gANWWallClosurePctTarget     = 0;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "DESwedish")
   {
      // DESwedish: Swedish Caroline — mobile field doctrine, urban barricade fallback in Baltic city
      gANWWallStrategy             = 5;
      gANWWallRadius               = 0;
      gANWWallGateCount            = 0;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 5;
      gANWWallSegmentLength        = 0;
      gANWWallTowerInterleave      = 0;
      gANWWallSecondaryStrategy    = 4;
      gANWWallVillagerCount        = 0;
      gANWWallForwardBiasFraction  = 0.0;
      gANWWallOuterRingDelta       = 0;
      gANWWallEarlyOutpostCount    = 3;
      gANWWallRepairAggressiveness = 0;
      gANWWallClosurePctTarget     = 0;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWCanadians")
   {
      // ANWCanadians (ANWCanadians): Lake-and-river defensive line, staying palisade till Fortress for cost, Frontier fallback
      gANWWallStrategy             = 0;
      gANWWallRadius               = 18;
      gANWWallGateCount            = 3;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 5;
      gANWWallSecondaryStrategy    = 3;
      gANWWallVillagerCount        = 6;
      gANWWallForwardBiasFraction  = 0.35;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 3;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWCalifornians")
   {
      // ANWCalifornians (ANWCalifornians): Californio rancho cavalry — vaqueros & lancers, mobile raiding, coastal fallback
      gANWWallStrategy             = 5;
      gANWWallRadius               = 0;
      gANWWallGateCount            = 0;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 5;
      gANWWallSegmentLength        = 0;
      gANWWallTowerInterleave      = 0;
      gANWWallSecondaryStrategy    = 2;
      gANWWallVillagerCount        = 0;
      gANWWallForwardBiasFraction  = 0.0;
      gANWWallOuterRingDelta       = 0;
      gANWWallEarlyOutpostCount    = 4;
      gANWWallRepairAggressiveness = 0;
      gANWWallClosurePctTarget     = 0;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWCentralAmericans")
   {
      // ANWCentralAmericans (ANWCentralAmericans): Federalist militia frontier palisade, cordillera-pass chokepoint fallback
      gANWWallStrategy             = 3;
      gANWWallRadius               = 18;
      gANWWallGateCount            = 3;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 4;
      gANWWallSecondaryStrategy    = 1;
      gANWWallVillagerCount        = 5;
      gANWWallForwardBiasFraction  = 0.4;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 3;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWBajaCalifornians")
   {
      // ANWBajaCalifornians (ANWBajaCalifornians): Desert-coast guerrilla coastal defense, chokepoint ambush fallback
      gANWWallStrategy             = 2;
      gANWWallRadius               = 16;
      gANWWallGateCount            = 2;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 4;
      gANWWallSecondaryStrategy    = 1;
      gANWWallVillagerCount        = 4;
      gANWWallForwardBiasFraction  = 0.3;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 3;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWRioGrande")
   {
      // ANWRioGrande (ANWRioGrande): Northern-frontier federalist cavalry, raid-and-retreat, mobile fallback
      gANWWallStrategy             = 3;
      gANWWallRadius               = 18;
      gANWWallGateCount            = 3;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 3;
      gANWWallSecondaryStrategy    = 5;
      gANWWallVillagerCount        = 5;
      gANWWallForwardBiasFraction  = 0.5;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 4;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWChileans")
   {
      // ANWChileans (ANWChileans): Andes-flank pocket fort, stone Colonial, choke fallback for cordillera pass
      gANWWallStrategy             = 0;
      gANWWallRadius               = 16;
      gANWWallGateCount            = 3;
      gANWWallTierAge2Stone        = true;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 5;
      gANWWallSecondaryStrategy    = 1;
      gANWWallVillagerCount        = 6;
      gANWWallForwardBiasFraction  = 0.3;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 2;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWPeruvians")
   {
      // ANWPeruvians (ANWPeruvians): Andean defensive Confederation pocket, similar to Chileans but tower-heavier
      gANWWallStrategy             = 0;
      gANWWallRadius               = 16;
      gANWWallGateCount            = 3;
      gANWWallTierAge2Stone        = true;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 6;
      gANWWallSecondaryStrategy    = 1;
      gANWWallVillagerCount        = 6;
      gANWWallForwardBiasFraction  = 0.3;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 2;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWEgyptians")
   {
      // ANWEgyptians (ANWEgyptians): Modernized Cairo citadel, Nile-bank with coastal supplement
      gANWWallStrategy             = 0;
      gANWWallRadius               = 22;
      gANWWallGateCount            = 4;
      gANWWallTierAge2Stone        = true;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 5;
      gANWWallSecondaryStrategy    = 2;
      gANWWallVillagerCount        = 7;
      gANWWallForwardBiasFraction  = 0.25;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 2;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWFinnish")
   {
      // ANWFinnish (ANWFinnish): Mannerheim Line — palisade-tier forward, dense outpost net, frontier fallback
      gANWWallStrategy             = 0;
      gANWWallRadius               = 18;
      gANWWallGateCount            = 2;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 6;
      gANWWallSecondaryStrategy    = 3;
      gANWWallVillagerCount        = 5;
      gANWWallForwardBiasFraction  = 0.45;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 4;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWHaitians")
   {
      // ANWHaitians (ANWHaitians): Mountain-pass guerrilla, palisade only, fallback to mobile if dispersed
      gANWWallStrategy             = 1;
      gANWWallRadius               = 10;
      gANWWallGateCount            = 2;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 4;
      gANWWallSecondaryStrategy    = 5;
      gANWWallVillagerCount        = 3;
      gANWWallForwardBiasFraction  = 0.7;
      gANWWallOuterRingDelta       = 0;
      gANWWallEarlyOutpostCount    = 4;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWIndonesians")
   {
      // ANWIndonesians (ANWIndonesians): Java Wars jungle/volcanic chokes, palisade, mobile fallback
      gANWWallStrategy             = 1;
      gANWWallRadius               = 10;
      gANWWallGateCount            = 2;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 3;
      gANWWallSecondaryStrategy    = 5;
      gANWWallVillagerCount        = 3;
      gANWWallForwardBiasFraction  = 0.75;
      gANWWallOuterRingDelta       = 0;
      gANWWallEarlyOutpostCount    = 4;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWMayans")
   {
      // ANWMayans (ANWMayans): Jungle pyramid chokes, jaguar ambush, late palisade only
      gANWWallStrategy             = 1;
      gANWWallRadius               = 10;
      gANWWallGateCount            = 2;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 3;
      gANWWallSecondaryStrategy    = 5;
      gANWWallVillagerCount        = 3;
      gANWWallForwardBiasFraction  = 0.7;
      gANWWallOuterRingDelta       = 0;
      gANWWallEarlyOutpostCount    = 4;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWBarbary")
   {
      // ANWBarbary (ANWBarbary): Corsair port walls land-side, gun batteries seaward, palisade-tier (raid economy)
      gANWWallStrategy             = 2;
      gANWWallRadius               = 20;
      gANWWallGateCount            = 3;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 6;
      gANWWallSecondaryStrategy    = 0;
      gANWWallVillagerCount        = 5;
      gANWWallForwardBiasFraction  = 0.35;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 3;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWSouthAfricans")
   {
      // ANWSouthAfricans (ANWSouthAfricans): Boer laager defense, palisade-tier, frontier fallback inland
      gANWWallStrategy             = 2;
      gANWWallRadius               = 18;
      gANWWallGateCount            = 3;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 5;
      gANWWallSecondaryStrategy    = 3;
      gANWWallVillagerCount        = 5;
      gANWWallForwardBiasFraction  = 0.3;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 3;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWBrazil")
   {
      // ANWBrazil (ANWBrazil): Pedro I Imperial Court — light palisade frontier, distributed plantations, coastal Atlantic fallback
      gANWWallStrategy             = 3;
      gANWWallRadius               = 20;
      gANWWallGateCount            = 4;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 4;
      gANWWallSecondaryStrategy    = 2;
      gANWWallVillagerCount        = 6;
      gANWWallForwardBiasFraction  = 0.3;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 2;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWRomanians")
   {
      // ANWRomanians (ANWRomanians): Carpathian palisade frontier, light towers, coastal fallback on Black Sea
      gANWWallStrategy             = 3;
      gANWWallRadius               = 18;
      gANWWallGateCount            = 4;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 3;
      gANWWallSecondaryStrategy    = 2;
      gANWWallVillagerCount        = 4;
      gANWWallForwardBiasFraction  = 0.5;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 3;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWRevFrance")
   {
      // ANWRevFrance (ANWRevFrance): Parisian Section barricade — Industrial trigger, tight inner ring, fanatical repair
      gANWWallStrategy             = 4;
      gANWWallRadius               = 10;
      gANWWallGateCount            = 3;
      gANWWallTierAge2Stone        = true;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 6;
      gANWWallSecondaryStrategy    = 0;
      gANWWallVillagerCount        = 5;
      gANWWallForwardBiasFraction  = 0.1;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 1;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWNapoleonicFrance")
   {
      // ANWNapoleonicFrance (ANWNapoleonicFrance): Grande Armée — no walls, dense outpost screen, urban barricade if forced back
      gANWWallStrategy             = 5;
      gANWWallRadius               = 0;
      gANWWallGateCount            = 0;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 5;
      gANWWallSegmentLength        = 0;
      gANWWallTowerInterleave      = 0;
      gANWWallSecondaryStrategy    = 4;
      gANWWallVillagerCount        = 0;
      gANWWallForwardBiasFraction  = 0.0;
      gANWWallOuterRingDelta       = 0;
      gANWWallEarlyOutpostCount    = 4;
      gANWWallRepairAggressiveness = 0;
      gANWWallClosurePctTarget     = 0;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWArgentines")
   {
      // ANWArgentines (ANWArgentines): Andean expedition no-walls, frontier palisade if cornered
      gANWWallStrategy             = 5;
      gANWWallRadius               = 0;
      gANWWallGateCount            = 0;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 5;
      gANWWallSegmentLength        = 0;
      gANWWallTowerInterleave      = 0;
      gANWWallSecondaryStrategy    = 3;
      gANWWallVillagerCount        = 0;
      gANWWallForwardBiasFraction  = 0.0;
      gANWWallOuterRingDelta       = 0;
      gANWWallEarlyOutpostCount    = 4;
      gANWWallRepairAggressiveness = 0;
      gANWWallClosurePctTarget     = 0;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWColumbians")
   {
      // ANWColumbians (ANWColumbians): Gran Colombia liberation column, no walls, frontier fallback
      gANWWallStrategy             = 5;
      gANWWallRadius               = 0;
      gANWWallGateCount            = 0;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 5;
      gANWWallSegmentLength        = 0;
      gANWWallTowerInterleave      = 0;
      gANWWallSecondaryStrategy    = 3;
      gANWWallVillagerCount        = 0;
      gANWWallForwardBiasFraction  = 0.0;
      gANWWallOuterRingDelta       = 0;
      gANWWallEarlyOutpostCount    = 4;
      gANWWallRepairAggressiveness = 0;
      gANWWallClosurePctTarget     = 0;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWHungarians")
   {
      // ANWHungarians (ANWHungarians): Magyar hussar — pure mobile, frontier fallback if pinned
      gANWWallStrategy             = 5;
      gANWWallRadius               = 0;
      gANWWallGateCount            = 0;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 5;
      gANWWallSegmentLength        = 0;
      gANWWallTowerInterleave      = 0;
      gANWWallSecondaryStrategy    = 3;
      gANWWallVillagerCount        = 0;
      gANWWallForwardBiasFraction  = 0.0;
      gANWWallOuterRingDelta       = 0;
      gANWWallEarlyOutpostCount    = 4;
      gANWWallRepairAggressiveness = 0;
      gANWWallClosurePctTarget     = 0;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWTexians")
   {
      // ANWTexians (ANWTexians): Texas Ranger — pure mobile cavalry, frontier fallback
      gANWWallStrategy             = 5;
      gANWWallRadius               = 0;
      gANWWallGateCount            = 0;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 5;
      gANWWallSegmentLength        = 0;
      gANWWallTowerInterleave      = 0;
      gANWWallSecondaryStrategy    = 3;
      gANWWallVillagerCount        = 0;
      gANWWallForwardBiasFraction  = 0.0;
      gANWWallOuterRingDelta       = 0;
      gANWWallEarlyOutpostCount    = 5;
      gANWWallRepairAggressiveness = 0;
      gANWWallClosurePctTarget     = 0;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWBritish")
   {
      // ANWBritish (ANWBritish): Channel-defense coastal — mirrors British (Elizabeth) exactly
      gANWWallStrategy             = 2;
      gANWWallRadius               = 22;
      gANWWallGateCount            = 4;
      gANWWallTierAge2Stone        = true;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 6;
      gANWWallSecondaryStrategy    = 0;
      gANWWallVillagerCount        = 6;
      gANWWallForwardBiasFraction  = 0.2;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 2;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWDutch")
   {
      // ANWDutch (ANWDutch): Dutch dyke-defense coastal — mirrors Dutch (Maurice) exactly
      gANWWallStrategy             = 2;
      gANWWallRadius               = 18;
      gANWWallGateCount            = 3;
      gANWWallTierAge2Stone        = true;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 7;
      gANWWallSecondaryStrategy    = 4;
      gANWWallVillagerCount        = 7;
      gANWWallForwardBiasFraction  = 0.15;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 2;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWPortuguese")
   {
      // ANWPortuguese (ANWPortuguese): Atlantic carrack coastal defense — mirrors Portuguese (Henry) exactly
      gANWWallStrategy             = 2;
      gANWWallRadius               = 22;
      gANWWallGateCount            = 4;
      gANWWallTierAge2Stone        = true;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 5;
      gANWWallSecondaryStrategy    = 0;
      gANWWallVillagerCount        = 6;
      gANWWallForwardBiasFraction  = 0.2;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 2;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWGermans")
   {
      // ANWGermans (ANWGermans): Prussian double-ring urban barricade — mirrors Germans (Frederick) exactly
      gANWWallStrategy             = 4;
      gANWWallRadius               = 14;
      gANWWallGateCount            = 3;
      gANWWallTierAge2Stone        = true;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 8;
      gANWWallSecondaryStrategy    = 0;
      gANWWallVillagerCount        = 7;
      gANWWallForwardBiasFraction  = 0.25;
      gANWWallOuterRingDelta       = 8;
      gANWWallEarlyOutpostCount    = 2;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWItalians")
   {
      // ANWItalians (ANWItalians): Risorgimento city walls urban barricade — mirrors DEItalians (Garibaldi) exactly
      gANWWallStrategy             = 4;
      gANWWallRadius               = 12;
      gANWWallGateCount            = 3;
      gANWWallTierAge2Stone        = true;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 5;
      gANWWallSecondaryStrategy    = 0;
      gANWWallVillagerCount        = 4;
      gANWWallForwardBiasFraction  = 0.15;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 1;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWMexicans")
   {
      // ANWMexicans (ANWMexicans): Insurgente town barricade — mirrors DEMexicans (Hidalgo) exactly
      gANWWallStrategy             = 4;
      gANWWallRadius               = 11;
      gANWWallGateCount            = 3;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 4;
      gANWWallSecondaryStrategy    = 3;
      gANWWallVillagerCount        = 4;
      gANWWallForwardBiasFraction  = 0.2;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 2;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWUSA")
   {
      // ANWUSA (ANWUSA): Continental Army camp barricade — mirrors DEAmericans (Washington) exactly
      gANWWallStrategy             = 4;
      gANWWallRadius               = 12;
      gANWWallGateCount            = 3;
      gANWWallTierAge2Stone        = true;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 5;
      gANWWallSecondaryStrategy    = 3;
      gANWWallVillagerCount        = 5;
      gANWWallForwardBiasFraction  = 0.2;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 2;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWHaudenosaunee")
   {
      // ANWHaudenosaunee (ANWHaudenosaunee): Iroquois Confederacy no-walls, choke fallback — mirrors XPIroquois (Hiawatha) exactly
      gANWWallStrategy             = 5;
      gANWWallRadius               = 0;
      gANWWallGateCount            = 0;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 5;
      gANWWallSegmentLength        = 0;
      gANWWallTowerInterleave      = 0;
      gANWWallSecondaryStrategy    = 1;
      gANWWallVillagerCount        = 0;
      gANWWallForwardBiasFraction  = 0.0;
      gANWWallOuterRingDelta       = 0;
      gANWWallEarlyOutpostCount    = 5;
      gANWWallRepairAggressiveness = 0;
      gANWWallClosurePctTarget     = 0;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWJapanese")
   {
      // ANWJapanese (ANWJapanese): Tokugawa daimyo field army no-walls — mirrors Japanese (Tokugawa) exactly
      gANWWallStrategy             = 5;
      gANWWallRadius               = 0;
      gANWWallGateCount            = 0;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 5;
      gANWWallSegmentLength        = 0;
      gANWWallTowerInterleave      = 0;
      gANWWallSecondaryStrategy    = 4;
      gANWWallVillagerCount        = 0;
      gANWWallForwardBiasFraction  = 0.0;
      gANWWallOuterRingDelta       = 0;
      gANWWallEarlyOutpostCount    = 3;
      gANWWallRepairAggressiveness = 0;
      gANWWallClosurePctTarget     = 0;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWLakota")
   {
      // ANWLakota (ANWLakota): Plains horse warrior no-walls — mirrors XPSioux (Chief Gall) exactly
      gANWWallStrategy             = 5;
      gANWWallRadius               = 0;
      gANWWallGateCount            = 0;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 5;
      gANWWallSegmentLength        = 0;
      gANWWallTowerInterleave      = 0;
      gANWWallSecondaryStrategy    = 3;
      gANWWallVillagerCount        = 0;
      gANWWallForwardBiasFraction  = 0.0;
      gANWWallOuterRingDelta       = 0;
      gANWWallEarlyOutpostCount    = 5;
      gANWWallRepairAggressiveness = 0;
      gANWWallClosurePctTarget     = 0;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWSpanish")
   {
      // ANWSpanish (ANWSpanish): Reconquista mobile column — mirrors Spanish (Isabella) exactly
      gANWWallStrategy             = 5;
      gANWWallRadius               = 0;
      gANWWallGateCount            = 0;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 5;
      gANWWallSegmentLength        = 0;
      gANWWallTowerInterleave      = 0;
      gANWWallSecondaryStrategy    = 2;
      gANWWallVillagerCount        = 0;
      gANWWallForwardBiasFraction  = 0.0;
      gANWWallOuterRingDelta       = 0;
      gANWWallEarlyOutpostCount    = 3;
      gANWWallRepairAggressiveness = 0;
      gANWWallClosurePctTarget     = 0;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWSwedes")
   {
      // ANWSwedes (ANWSwedes): Swedish Caroline mobile doctrine — mirrors DESwedish (Gustavus) exactly
      gANWWallStrategy             = 5;
      gANWWallRadius               = 0;
      gANWWallGateCount            = 0;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 5;
      gANWWallSegmentLength        = 0;
      gANWWallTowerInterleave      = 0;
      gANWWallSecondaryStrategy    = 4;
      gANWWallVillagerCount        = 0;
      gANWWallForwardBiasFraction  = 0.0;
      gANWWallOuterRingDelta       = 0;
      gANWWallEarlyOutpostCount    = 3;
      gANWWallRepairAggressiveness = 0;
      gANWWallClosurePctTarget     = 0;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWHausa")
   {
      // ANWHausa (ANWHausa): Hausa caravanserai frontier palisade — mirrors DEHausa (Usman) exactly
      gANWWallStrategy             = 3;
      gANWWallRadius               = 18;
      gANWWallGateCount            = 5;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 3;
      gANWWallSecondaryStrategy    = 5;
      gANWWallVillagerCount        = 4;
      gANWWallForwardBiasFraction  = 0.55;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 4;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWChinese")
   {
      // ANWChinese (ANWChinese): Great Wall fortress doctrine — mirrors Chinese (Kangxi) exactly
      gANWWallStrategy             = 0;
      gANWWallRadius               = 18;
      gANWWallGateCount            = 3;
      gANWWallTierAge2Stone        = true;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 5;
      gANWWallSecondaryStrategy    = 1;
      gANWWallVillagerCount        = 7;
      gANWWallForwardBiasFraction  = 0.4;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 2;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWEthiopians")
   {
      // ANWEthiopians (ANWEthiopians): Highland citadel fortress — mirrors DEEthiopians (Menelik) exactly
      gANWWallStrategy             = 0;
      gANWWallRadius               = 20;
      gANWWallGateCount            = 3;
      gANWWallTierAge2Stone        = false;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 4;
      gANWWallSecondaryStrategy    = 1;
      gANWWallVillagerCount        = 5;
      gANWWallForwardBiasFraction  = 0.4;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 3;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWIndians")
   {
      // ANWIndians (ANWIndians): Maratha hill-fort citadel — mirrors Indians (Shivaji/Akbar) exactly
      gANWWallStrategy             = 0;
      gANWWallRadius               = 16;
      gANWWallGateCount            = 2;
      gANWWallTierAge2Stone        = true;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 7;
      gANWWallSecondaryStrategy    = 1;
      gANWWallVillagerCount        = 7;
      gANWWallForwardBiasFraction  = 0.35;
      gANWWallOuterRingDelta       = 4;
      gANWWallEarlyOutpostCount    = 2;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWMaltese")
   {
      // ANWMaltese (ANWMaltese): Order of St John siege fortress — mirrors DEMaltese (Valette) exactly
      gANWWallStrategy             = 0;
      gANWWallRadius               = 16;
      gANWWallGateCount            = 3;
      gANWWallTierAge2Stone        = true;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 8;
      gANWWallSecondaryStrategy    = 2;
      gANWWallVillagerCount        = 10;
      gANWWallForwardBiasFraction  = 0.15;
      gANWWallOuterRingDelta       = 6;
      gANWWallEarlyOutpostCount    = 1;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWOttomans")
   {
      // ANWOttomans (ANWOttomans): Janissary-engineer double ring — mirrors Ottomans (Suleiman) exactly
      gANWWallStrategy             = 0;
      gANWWallRadius               = 20;
      gANWWallGateCount            = 4;
      gANWWallTierAge2Stone        = true;
      gANWWallTriggerAge           = 2;
      gANWWallSegmentLength        = 20;
      gANWWallTowerInterleave      = 6;
      gANWWallSecondaryStrategy    = 4;
      gANWWallVillagerCount        = 8;
      gANWWallForwardBiasFraction  = 0.3;
      gANWWallOuterRingDelta       = 6;
      gANWWallEarlyOutpostCount    = 2;
      gANWWallRepairAggressiveness = 3;
      gANWWallClosurePctTarget     = 100;
      gANWWallNoWaterBuild         = true;
   }
   else
   {
      // Unknown civ — leave defaults from aiHeader.xs.
      anwProbe("wall.knobs", "civ=" + civKey + " status=default");
      return;
   }

   // One-shot probe so validators can confirm per-civ knob set reached the engine.
   anwProbe("wall.knobs",
      "civ=" + civKey +
      " strategy=" + gANWWallStrategy +
      " r=" + gANWWallRadius +
      " g=" + gANWWallGateCount +
      " stoneA2=" + gANWWallTierAge2Stone +
      " trig=" + gANWWallTriggerAge +
      " segL=" + gANWWallSegmentLength +
      " tow=" + gANWWallTowerInterleave +
      " sec=" + gANWWallSecondaryStrategy +
      " v=" + gANWWallVillagerCount +
      " fwd=" + gANWWallForwardBiasFraction +
      " outer=" + gANWWallOuterRingDelta +
      " outp=" + gANWWallEarlyOutpostCount +
      " rep=" + gANWWallRepairAggressiveness +
      " clo=" + gANWWallClosurePctTarget +
      " noW=" + gANWWallNoWaterBuild);
}
