// AUTO-GENERATED by tools/ai_design/wall_knob_calibration.py
// 40-civ × 14-knob calibration table.
// Edit the .py file and re-emit; do not hand-edit this XS file.
//
// Called from aiLoaderStandard.xs::preInit() AFTER initLeader<Name>()
// so per-civ knobs override any strategy defaults set in leader files.

void llSetWallKnobsForCiv(void)
{
   // Resolve civ key — use kbGetCivName so we can distinguish
   // base civs from revolution-spawn civs (ANW*).
   string civKey = kbGetCivName(cMyCiv);

   if (civKey == "DEInca")
   {
      // DEInca: Tight terraced core, early stone, valley-mouth chokes secondary
      gLLWallStrategy             = 0;
      gLLWallRadius               = 14;
      gLLWallGateCount            = 2;
      gLLWallTierAge2Stone        = true;
      gLLWallTriggerAge           = 2;
      gLLWallSegmentLength        = 20;
      gLLWallTowerInterleave      = 4;
      gLLWallSecondaryStrategy    = 1;
      gLLWallVillagerCount        = 8;
      gLLWallForwardBiasFraction  = 0.2;
      gLLWallOuterRingDelta       = 4;
      gLLWallEarlyOutpostCount    = 2;
      gLLWallRepairAggressiveness = 3;
      gLLWallClosurePctTarget     = 100;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "Germans")
   {
      // Germans: Prussian double-ring around drillyard, tower-dense, strict closure
      gLLWallStrategy             = 4;
      gLLWallRadius               = 14;
      gLLWallGateCount            = 3;
      gLLWallTierAge2Stone        = true;
      gLLWallTriggerAge           = 2;
      gLLWallSegmentLength        = 20;
      gLLWallTowerInterleave      = 8;
      gLLWallSecondaryStrategy    = 0;
      gLLWallVillagerCount        = 7;
      gLLWallForwardBiasFraction  = 0.25;
      gLLWallOuterRingDelta       = 8;
      gLLWallEarlyOutpostCount    = 2;
      gLLWallRepairAggressiveness = 3;
      gLLWallClosurePctTarget     = 100;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "Ottomans")
   {
      // Ottomans: Janissary-engineer double ring, open gate count for trade, outer ring for siege absorption
      gLLWallStrategy             = 0;
      gLLWallRadius               = 20;
      gLLWallGateCount            = 4;
      gLLWallTierAge2Stone        = true;
      gLLWallTriggerAge           = 2;
      gLLWallSegmentLength        = 20;
      gLLWallTowerInterleave      = 6;
      gLLWallSecondaryStrategy    = 4;
      gLLWallVillagerCount        = 8;
      gLLWallForwardBiasFraction  = 0.3;
      gLLWallOuterRingDelta       = 6;
      gLLWallEarlyOutpostCount    = 2;
      gLLWallRepairAggressiveness = 3;
      gLLWallClosurePctTarget     = 100;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "DEMaltese")
   {
      // DEMaltese: Order of St John siege doctrine, tower spam, double ring, coastal Coastal fallback
      gLLWallStrategy             = 0;
      gLLWallRadius               = 16;
      gLLWallGateCount            = 3;
      gLLWallTierAge2Stone        = true;
      gLLWallTriggerAge           = 2;
      gLLWallSegmentLength        = 20;
      gLLWallTowerInterleave      = 8;
      gLLWallSecondaryStrategy    = 2;
      gLLWallVillagerCount        = 10;
      gLLWallForwardBiasFraction  = 0.15;
      gLLWallOuterRingDelta       = 6;
      gLLWallEarlyOutpostCount    = 1;
      gLLWallRepairAggressiveness = 3;
      gLLWallClosurePctTarget     = 100;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "Chinese")
   {
      // Chinese: Wall doctrine: long defensive spine with watchtowers, choke fallback for hills
      gLLWallStrategy             = 0;
      gLLWallRadius               = 18;
      gLLWallGateCount            = 3;
      gLLWallTierAge2Stone        = true;
      gLLWallTriggerAge           = 2;
      gLLWallSegmentLength        = 20;
      gLLWallTowerInterleave      = 5;
      gLLWallSecondaryStrategy    = 1;
      gLLWallVillagerCount        = 7;
      gLLWallForwardBiasFraction  = 0.4;
      gLLWallOuterRingDelta       = 4;
      gLLWallEarlyOutpostCount    = 2;
      gLLWallRepairAggressiveness = 3;
      gLLWallClosurePctTarget     = 100;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "French")
   {
      // French: Vauban-style star fort, narrow gates, royal court depth
      gLLWallStrategy             = 0;
      gLLWallRadius               = 18;
      gLLWallGateCount            = 2;
      gLLWallTierAge2Stone        = true;
      gLLWallTriggerAge           = 2;
      gLLWallSegmentLength        = 20;
      gLLWallTowerInterleave      = 7;
      gLLWallSecondaryStrategy    = 2;
      gLLWallVillagerCount        = 9;
      gLLWallForwardBiasFraction  = 0.2;
      gLLWallOuterRingDelta       = 4;
      gLLWallEarlyOutpostCount    = 2;
      gLLWallRepairAggressiveness = 3;
      gLLWallClosurePctTarget     = 100;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "Indians")
   {
      // Indians: Maratha hill-fort citadel, dense tower interleave, ghat-pass choke fallback
      gLLWallStrategy             = 0;
      gLLWallRadius               = 16;
      gLLWallGateCount            = 2;
      gLLWallTierAge2Stone        = true;
      gLLWallTriggerAge           = 2;
      gLLWallSegmentLength        = 20;
      gLLWallTowerInterleave      = 7;
      gLLWallSecondaryStrategy    = 1;
      gLLWallVillagerCount        = 7;
      gLLWallForwardBiasFraction  = 0.35;
      gLLWallOuterRingDelta       = 4;
      gLLWallEarlyOutpostCount    = 2;
      gLLWallRepairAggressiveness = 3;
      gLLWallClosurePctTarget     = 100;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "DEEthiopians")
   {
      // DEEthiopians: Highland fortress with long sparse defensive lines, late stone-tier (resource-scarce)
      gLLWallStrategy             = 0;
      gLLWallRadius               = 20;
      gLLWallGateCount            = 3;
      gLLWallTierAge2Stone        = false;
      gLLWallTriggerAge           = 2;
      gLLWallSegmentLength        = 20;
      gLLWallTowerInterleave      = 4;
      gLLWallSecondaryStrategy    = 1;
      gLLWallVillagerCount        = 5;
      gLLWallForwardBiasFraction  = 0.4;
      gLLWallOuterRingDelta       = 4;
      gLLWallEarlyOutpostCount    = 3;
      gLLWallRepairAggressiveness = 3;
      gLLWallClosurePctTarget     = 100;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "XPAztec")
   {
      // XPAztec: Causeway/jungle choke walls, mostly War Hut substitution, late + sparse
      gLLWallStrategy             = 1;
      gLLWallRadius               = 10;
      gLLWallGateCount            = 2;
      gLLWallTierAge2Stone        = false;
      gLLWallTriggerAge           = 2;
      gLLWallSegmentLength        = 20;
      gLLWallTowerInterleave      = 3;
      gLLWallSecondaryStrategy    = 5;
      gLLWallVillagerCount        = 3;
      gLLWallForwardBiasFraction  = 0.75;
      gLLWallOuterRingDelta       = 0;
      gLLWallEarlyOutpostCount    = 4;
      gLLWallRepairAggressiveness = 3;
      gLLWallClosurePctTarget     = 100;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "British")
   {
      // British: Channel-defense coastal, dense towers facing land, gates open for trade
      gLLWallStrategy             = 2;
      gLLWallRadius               = 22;
      gLLWallGateCount            = 4;
      gLLWallTierAge2Stone        = true;
      gLLWallTriggerAge           = 2;
      gLLWallSegmentLength        = 20;
      gLLWallTowerInterleave      = 6;
      gLLWallSecondaryStrategy    = 0;
      gLLWallVillagerCount        = 6;
      gLLWallForwardBiasFraction  = 0.2;
      gLLWallOuterRingDelta       = 4;
      gLLWallEarlyOutpostCount    = 2;
      gLLWallRepairAggressiveness = 3;
      gLLWallClosurePctTarget     = 100;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "Portuguese")
   {
      // Portuguese: Atlantic carrack-defense coastal, gates face inland trade, water is wide-open by design
      gLLWallStrategy             = 2;
      gLLWallRadius               = 22;
      gLLWallGateCount            = 4;
      gLLWallTierAge2Stone        = true;
      gLLWallTriggerAge           = 2;
      gLLWallSegmentLength        = 20;
      gLLWallTowerInterleave      = 5;
      gLLWallSecondaryStrategy    = 0;
      gLLWallVillagerCount        = 6;
      gLLWallForwardBiasFraction  = 0.2;
      gLLWallOuterRingDelta       = 4;
      gLLWallEarlyOutpostCount    = 2;
      gLLWallRepairAggressiveness = 3;
      gLLWallClosurePctTarget     = 100;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "Dutch")
   {
      // Dutch: Dutch dyke-defense, narrow gates, tower-spam, urban barricade fallback in city core
      gLLWallStrategy             = 2;
      gLLWallRadius               = 18;
      gLLWallGateCount            = 3;
      gLLWallTierAge2Stone        = true;
      gLLWallTriggerAge           = 2;
      gLLWallSegmentLength        = 20;
      gLLWallTowerInterleave      = 7;
      gLLWallSecondaryStrategy    = 4;
      gLLWallVillagerCount        = 7;
      gLLWallForwardBiasFraction  = 0.15;
      gLLWallOuterRingDelta       = 4;
      gLLWallEarlyOutpostCount    = 2;
      gLLWallRepairAggressiveness = 3;
      gLLWallClosurePctTarget     = 100;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "DEHausa")
   {
      // DEHausa: Hausa caravanserai frontier, palisade only, mobile fallback for jihad raids
      gLLWallStrategy             = 3;
      gLLWallRadius               = 18;
      gLLWallGateCount            = 5;
      gLLWallTierAge2Stone        = false;
      gLLWallTriggerAge           = 2;
      gLLWallSegmentLength        = 20;
      gLLWallTowerInterleave      = 3;
      gLLWallSecondaryStrategy    = 5;
      gLLWallVillagerCount        = 4;
      gLLWallForwardBiasFraction  = 0.55;
      gLLWallOuterRingDelta       = 4;
      gLLWallEarlyOutpostCount    = 4;
      gLLWallRepairAggressiveness = 3;
      gLLWallClosurePctTarget     = 100;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "Russians")
   {
      // Russians: Kremlin-style palisade-then-stone with sentinel towers on steppe frontier
      gLLWallStrategy             = 3;
      gLLWallRadius               = 22;
      gLLWallGateCount            = 4;
      gLLWallTierAge2Stone        = false;
      gLLWallTriggerAge           = 2;
      gLLWallSegmentLength        = 20;
      gLLWallTowerInterleave      = 4;
      gLLWallSecondaryStrategy    = 0;
      gLLWallVillagerCount        = 5;
      gLLWallForwardBiasFraction  = 0.45;
      gLLWallOuterRingDelta       = 4;
      gLLWallEarlyOutpostCount    = 4;
      gLLWallRepairAggressiveness = 3;
      gLLWallClosurePctTarget     = 100;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "DEItalians")
   {
      // DEItalians: Risorgimento city walls, Colonial trigger, tight ring with bell-tower observation
      gLLWallStrategy             = 4;
      gLLWallRadius               = 12;
      gLLWallGateCount            = 3;
      gLLWallTierAge2Stone        = true;
      gLLWallTriggerAge           = 2;
      gLLWallSegmentLength        = 20;
      gLLWallTowerInterleave      = 5;
      gLLWallSecondaryStrategy    = 0;
      gLLWallVillagerCount        = 4;
      gLLWallForwardBiasFraction  = 0.15;
      gLLWallOuterRingDelta       = 4;
      gLLWallEarlyOutpostCount    = 1;
      gLLWallRepairAggressiveness = 3;
      gLLWallClosurePctTarget     = 100;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "DEMexicans")
   {
      // DEMexicans: Insurgente town barricade, palisade-tier (resource constraint), frontier fallback
      gLLWallStrategy             = 4;
      gLLWallRadius               = 11;
      gLLWallGateCount            = 3;
      gLLWallTierAge2Stone        = false;
      gLLWallTriggerAge           = 2;
      gLLWallSegmentLength        = 20;
      gLLWallTowerInterleave      = 4;
      gLLWallSecondaryStrategy    = 3;
      gLLWallVillagerCount        = 4;
      gLLWallForwardBiasFraction  = 0.2;
      gLLWallOuterRingDelta       = 4;
      gLLWallEarlyOutpostCount    = 2;
      gLLWallRepairAggressiveness = 3;
      gLLWallClosurePctTarget     = 100;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "DEAmericans")
   {
      // DEAmericans: Continental Army camp barricade, stone Colonial, frontier-palisade fallback in field
      gLLWallStrategy             = 4;
      gLLWallRadius               = 12;
      gLLWallGateCount            = 3;
      gLLWallTierAge2Stone        = true;
      gLLWallTriggerAge           = 2;
      gLLWallSegmentLength        = 20;
      gLLWallTowerInterleave      = 5;
      gLLWallSecondaryStrategy    = 3;
      gLLWallVillagerCount        = 5;
      gLLWallForwardBiasFraction  = 0.2;
      gLLWallOuterRingDelta       = 4;
      gLLWallEarlyOutpostCount    = 2;
      gLLWallRepairAggressiveness = 3;
      gLLWallClosurePctTarget     = 100;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "XPIroquois")
   {
      // XPIroquois: Iroquois Confederacy — longhouse village, no perimeter walls, choke fallback at portages
      gLLWallStrategy             = 5;
      gLLWallRadius               = 0;
      gLLWallGateCount            = 0;
      gLLWallTierAge2Stone        = false;
      gLLWallTriggerAge           = 5;
      gLLWallSegmentLength        = 0;
      gLLWallTowerInterleave      = 0;
      gLLWallSecondaryStrategy    = 1;
      gLLWallVillagerCount        = 0;
      gLLWallForwardBiasFraction  = 0.0;
      gLLWallOuterRingDelta       = 0;
      gLLWallEarlyOutpostCount    = 5;
      gLLWallRepairAggressiveness = 0;
      gLLWallClosurePctTarget     = 0;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "Japanese")
   {
      // Japanese: Tokugawa daimyō field army, no walls, urban barricade fallback at castle
      gLLWallStrategy             = 5;
      gLLWallRadius               = 0;
      gLLWallGateCount            = 0;
      gLLWallTierAge2Stone        = false;
      gLLWallTriggerAge           = 5;
      gLLWallSegmentLength        = 0;
      gLLWallTowerInterleave      = 0;
      gLLWallSecondaryStrategy    = 4;
      gLLWallVillagerCount        = 0;
      gLLWallForwardBiasFraction  = 0.0;
      gLLWallOuterRingDelta       = 0;
      gLLWallEarlyOutpostCount    = 3;
      gLLWallRepairAggressiveness = 0;
      gLLWallClosurePctTarget     = 0;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "XPSioux")
   {
      // XPSioux: Plains horse warrior — pure mobile, outpost screen, frontier fallback
      gLLWallStrategy             = 5;
      gLLWallRadius               = 0;
      gLLWallGateCount            = 0;
      gLLWallTierAge2Stone        = false;
      gLLWallTriggerAge           = 5;
      gLLWallSegmentLength        = 0;
      gLLWallTowerInterleave      = 0;
      gLLWallSecondaryStrategy    = 3;
      gLLWallVillagerCount        = 0;
      gLLWallForwardBiasFraction  = 0.0;
      gLLWallOuterRingDelta       = 0;
      gLLWallEarlyOutpostCount    = 5;
      gLLWallRepairAggressiveness = 0;
      gLLWallClosurePctTarget     = 0;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "Spanish")
   {
      // Spanish: Reconquista mobile column, coastal fallback (Iberian peninsula)
      gLLWallStrategy             = 5;
      gLLWallRadius               = 0;
      gLLWallGateCount            = 0;
      gLLWallTierAge2Stone        = false;
      gLLWallTriggerAge           = 5;
      gLLWallSegmentLength        = 0;
      gLLWallTowerInterleave      = 0;
      gLLWallSecondaryStrategy    = 2;
      gLLWallVillagerCount        = 0;
      gLLWallForwardBiasFraction  = 0.0;
      gLLWallOuterRingDelta       = 0;
      gLLWallEarlyOutpostCount    = 3;
      gLLWallRepairAggressiveness = 0;
      gLLWallClosurePctTarget     = 0;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "DESwedish")
   {
      // DESwedish: Swedish Caroline — mobile field doctrine, urban barricade fallback in Baltic city
      gLLWallStrategy             = 5;
      gLLWallRadius               = 0;
      gLLWallGateCount            = 0;
      gLLWallTierAge2Stone        = false;
      gLLWallTriggerAge           = 5;
      gLLWallSegmentLength        = 0;
      gLLWallTowerInterleave      = 0;
      gLLWallSecondaryStrategy    = 4;
      gLLWallVillagerCount        = 0;
      gLLWallForwardBiasFraction  = 0.0;
      gLLWallOuterRingDelta       = 0;
      gLLWallEarlyOutpostCount    = 3;
      gLLWallRepairAggressiveness = 0;
      gLLWallClosurePctTarget     = 0;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWCanadians")
   {
      // ANWCanadians (ANWCanadians): Lake-and-river defensive line, staying palisade till Fortress for cost, Frontier fallback
      gLLWallStrategy             = 0;
      gLLWallRadius               = 18;
      gLLWallGateCount            = 3;
      gLLWallTierAge2Stone        = false;
      gLLWallTriggerAge           = 2;
      gLLWallSegmentLength        = 20;
      gLLWallTowerInterleave      = 5;
      gLLWallSecondaryStrategy    = 3;
      gLLWallVillagerCount        = 6;
      gLLWallForwardBiasFraction  = 0.35;
      gLLWallOuterRingDelta       = 4;
      gLLWallEarlyOutpostCount    = 3;
      gLLWallRepairAggressiveness = 3;
      gLLWallClosurePctTarget     = 100;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWChileans")
   {
      // ANWChileans (ANWChileans): Andes-flank pocket fort, stone Colonial, choke fallback for cordillera pass
      gLLWallStrategy             = 0;
      gLLWallRadius               = 16;
      gLLWallGateCount            = 3;
      gLLWallTierAge2Stone        = true;
      gLLWallTriggerAge           = 2;
      gLLWallSegmentLength        = 20;
      gLLWallTowerInterleave      = 5;
      gLLWallSecondaryStrategy    = 1;
      gLLWallVillagerCount        = 6;
      gLLWallForwardBiasFraction  = 0.3;
      gLLWallOuterRingDelta       = 4;
      gLLWallEarlyOutpostCount    = 2;
      gLLWallRepairAggressiveness = 3;
      gLLWallClosurePctTarget     = 100;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWPeruvians")
   {
      // ANWPeruvians (ANWPeruvians): Andean defensive Confederation pocket, similar to Chileans but tower-heavier
      gLLWallStrategy             = 0;
      gLLWallRadius               = 16;
      gLLWallGateCount            = 3;
      gLLWallTierAge2Stone        = true;
      gLLWallTriggerAge           = 2;
      gLLWallSegmentLength        = 20;
      gLLWallTowerInterleave      = 6;
      gLLWallSecondaryStrategy    = 1;
      gLLWallVillagerCount        = 6;
      gLLWallForwardBiasFraction  = 0.3;
      gLLWallOuterRingDelta       = 4;
      gLLWallEarlyOutpostCount    = 2;
      gLLWallRepairAggressiveness = 3;
      gLLWallClosurePctTarget     = 100;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWEgyptians")
   {
      // ANWEgyptians (ANWEgyptians): Modernized Cairo citadel, Nile-bank with coastal supplement
      gLLWallStrategy             = 0;
      gLLWallRadius               = 22;
      gLLWallGateCount            = 4;
      gLLWallTierAge2Stone        = true;
      gLLWallTriggerAge           = 2;
      gLLWallSegmentLength        = 20;
      gLLWallTowerInterleave      = 5;
      gLLWallSecondaryStrategy    = 2;
      gLLWallVillagerCount        = 7;
      gLLWallForwardBiasFraction  = 0.25;
      gLLWallOuterRingDelta       = 4;
      gLLWallEarlyOutpostCount    = 2;
      gLLWallRepairAggressiveness = 3;
      gLLWallClosurePctTarget     = 100;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWFinnish")
   {
      // ANWFinnish (ANWFinnish): Mannerheim Line — palisade-tier forward, dense outpost net, frontier fallback
      gLLWallStrategy             = 0;
      gLLWallRadius               = 18;
      gLLWallGateCount            = 2;
      gLLWallTierAge2Stone        = false;
      gLLWallTriggerAge           = 2;
      gLLWallSegmentLength        = 20;
      gLLWallTowerInterleave      = 6;
      gLLWallSecondaryStrategy    = 3;
      gLLWallVillagerCount        = 5;
      gLLWallForwardBiasFraction  = 0.45;
      gLLWallOuterRingDelta       = 4;
      gLLWallEarlyOutpostCount    = 4;
      gLLWallRepairAggressiveness = 3;
      gLLWallClosurePctTarget     = 100;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWHaitians")
   {
      // ANWHaitians (ANWHaitians): Mountain-pass guerrilla, palisade only, fallback to mobile if dispersed
      gLLWallStrategy             = 1;
      gLLWallRadius               = 10;
      gLLWallGateCount            = 2;
      gLLWallTierAge2Stone        = false;
      gLLWallTriggerAge           = 2;
      gLLWallSegmentLength        = 20;
      gLLWallTowerInterleave      = 4;
      gLLWallSecondaryStrategy    = 5;
      gLLWallVillagerCount        = 3;
      gLLWallForwardBiasFraction  = 0.7;
      gLLWallOuterRingDelta       = 0;
      gLLWallEarlyOutpostCount    = 4;
      gLLWallRepairAggressiveness = 3;
      gLLWallClosurePctTarget     = 100;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWIndonesians")
   {
      // ANWIndonesians (ANWIndonesians): Java Wars jungle/volcanic chokes, palisade, mobile fallback
      gLLWallStrategy             = 1;
      gLLWallRadius               = 10;
      gLLWallGateCount            = 2;
      gLLWallTierAge2Stone        = false;
      gLLWallTriggerAge           = 2;
      gLLWallSegmentLength        = 20;
      gLLWallTowerInterleave      = 3;
      gLLWallSecondaryStrategy    = 5;
      gLLWallVillagerCount        = 3;
      gLLWallForwardBiasFraction  = 0.75;
      gLLWallOuterRingDelta       = 0;
      gLLWallEarlyOutpostCount    = 4;
      gLLWallRepairAggressiveness = 3;
      gLLWallClosurePctTarget     = 100;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWMayans")
   {
      // ANWMayans (ANWMayans): Jungle pyramid chokes, jaguar ambush, late palisade only
      gLLWallStrategy             = 1;
      gLLWallRadius               = 10;
      gLLWallGateCount            = 2;
      gLLWallTierAge2Stone        = false;
      gLLWallTriggerAge           = 2;
      gLLWallSegmentLength        = 20;
      gLLWallTowerInterleave      = 3;
      gLLWallSecondaryStrategy    = 5;
      gLLWallVillagerCount        = 3;
      gLLWallForwardBiasFraction  = 0.7;
      gLLWallOuterRingDelta       = 0;
      gLLWallEarlyOutpostCount    = 4;
      gLLWallRepairAggressiveness = 3;
      gLLWallClosurePctTarget     = 100;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWBarbary")
   {
      // ANWBarbary (ANWBarbary): Corsair port walls land-side, gun batteries seaward, palisade-tier (raid economy)
      gLLWallStrategy             = 2;
      gLLWallRadius               = 20;
      gLLWallGateCount            = 3;
      gLLWallTierAge2Stone        = false;
      gLLWallTriggerAge           = 2;
      gLLWallSegmentLength        = 20;
      gLLWallTowerInterleave      = 6;
      gLLWallSecondaryStrategy    = 0;
      gLLWallVillagerCount        = 5;
      gLLWallForwardBiasFraction  = 0.35;
      gLLWallOuterRingDelta       = 4;
      gLLWallEarlyOutpostCount    = 3;
      gLLWallRepairAggressiveness = 3;
      gLLWallClosurePctTarget     = 100;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWSouthAfricans")
   {
      // ANWSouthAfricans (ANWSouthAfricans): Boer laager defense, palisade-tier, frontier fallback inland
      gLLWallStrategy             = 2;
      gLLWallRadius               = 18;
      gLLWallGateCount            = 3;
      gLLWallTierAge2Stone        = false;
      gLLWallTriggerAge           = 2;
      gLLWallSegmentLength        = 20;
      gLLWallTowerInterleave      = 5;
      gLLWallSecondaryStrategy    = 3;
      gLLWallVillagerCount        = 5;
      gLLWallForwardBiasFraction  = 0.3;
      gLLWallOuterRingDelta       = 4;
      gLLWallEarlyOutpostCount    = 3;
      gLLWallRepairAggressiveness = 3;
      gLLWallClosurePctTarget     = 100;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWBrazil")
   {
      // ANWBrazil (ANWBrazil): Pedro I Imperial Court — light palisade frontier, distributed plantations, coastal Atlantic fallback
      gLLWallStrategy             = 3;
      gLLWallRadius               = 20;
      gLLWallGateCount            = 4;
      gLLWallTierAge2Stone        = false;
      gLLWallTriggerAge           = 2;
      gLLWallSegmentLength        = 20;
      gLLWallTowerInterleave      = 4;
      gLLWallSecondaryStrategy    = 2;
      gLLWallVillagerCount        = 6;
      gLLWallForwardBiasFraction  = 0.3;
      gLLWallOuterRingDelta       = 4;
      gLLWallEarlyOutpostCount    = 2;
      gLLWallRepairAggressiveness = 3;
      gLLWallClosurePctTarget     = 100;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWRomanians")
   {
      // ANWRomanians (ANWRomanians): Carpathian palisade frontier, light towers, coastal fallback on Black Sea
      gLLWallStrategy             = 3;
      gLLWallRadius               = 18;
      gLLWallGateCount            = 4;
      gLLWallTierAge2Stone        = false;
      gLLWallTriggerAge           = 2;
      gLLWallSegmentLength        = 20;
      gLLWallTowerInterleave      = 3;
      gLLWallSecondaryStrategy    = 2;
      gLLWallVillagerCount        = 4;
      gLLWallForwardBiasFraction  = 0.5;
      gLLWallOuterRingDelta       = 4;
      gLLWallEarlyOutpostCount    = 3;
      gLLWallRepairAggressiveness = 3;
      gLLWallClosurePctTarget     = 100;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWRevFrance")
   {
      // ANWRevFrance (ANWRevFrance): Parisian Section barricade — Industrial trigger, tight inner ring, fanatical repair
      gLLWallStrategy             = 4;
      gLLWallRadius               = 10;
      gLLWallGateCount            = 3;
      gLLWallTierAge2Stone        = true;
      gLLWallTriggerAge           = 2;
      gLLWallSegmentLength        = 20;
      gLLWallTowerInterleave      = 6;
      gLLWallSecondaryStrategy    = 0;
      gLLWallVillagerCount        = 5;
      gLLWallForwardBiasFraction  = 0.1;
      gLLWallOuterRingDelta       = 4;
      gLLWallEarlyOutpostCount    = 1;
      gLLWallRepairAggressiveness = 3;
      gLLWallClosurePctTarget     = 100;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWNapoleonicFrance")
   {
      // ANWNapoleonicFrance (ANWNapoleonicFrance): Grande Armée — no walls, dense outpost screen, urban barricade if forced back
      gLLWallStrategy             = 5;
      gLLWallRadius               = 0;
      gLLWallGateCount            = 0;
      gLLWallTierAge2Stone        = false;
      gLLWallTriggerAge           = 5;
      gLLWallSegmentLength        = 0;
      gLLWallTowerInterleave      = 0;
      gLLWallSecondaryStrategy    = 4;
      gLLWallVillagerCount        = 0;
      gLLWallForwardBiasFraction  = 0.0;
      gLLWallOuterRingDelta       = 0;
      gLLWallEarlyOutpostCount    = 4;
      gLLWallRepairAggressiveness = 0;
      gLLWallClosurePctTarget     = 0;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWArgentines")
   {
      // ANWArgentines (ANWArgentines): Andean expedition no-walls, frontier palisade if cornered
      gLLWallStrategy             = 5;
      gLLWallRadius               = 0;
      gLLWallGateCount            = 0;
      gLLWallTierAge2Stone        = false;
      gLLWallTriggerAge           = 5;
      gLLWallSegmentLength        = 0;
      gLLWallTowerInterleave      = 0;
      gLLWallSecondaryStrategy    = 3;
      gLLWallVillagerCount        = 0;
      gLLWallForwardBiasFraction  = 0.0;
      gLLWallOuterRingDelta       = 0;
      gLLWallEarlyOutpostCount    = 4;
      gLLWallRepairAggressiveness = 0;
      gLLWallClosurePctTarget     = 0;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWColumbians")
   {
      // ANWColumbians (ANWColumbians): Gran Colombia liberation column, no walls, frontier fallback
      gLLWallStrategy             = 5;
      gLLWallRadius               = 0;
      gLLWallGateCount            = 0;
      gLLWallTierAge2Stone        = false;
      gLLWallTriggerAge           = 5;
      gLLWallSegmentLength        = 0;
      gLLWallTowerInterleave      = 0;
      gLLWallSecondaryStrategy    = 3;
      gLLWallVillagerCount        = 0;
      gLLWallForwardBiasFraction  = 0.0;
      gLLWallOuterRingDelta       = 0;
      gLLWallEarlyOutpostCount    = 4;
      gLLWallRepairAggressiveness = 0;
      gLLWallClosurePctTarget     = 0;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWHungarians")
   {
      // ANWHungarians (ANWHungarians): Magyar hussar — pure mobile, frontier fallback if pinned
      gLLWallStrategy             = 5;
      gLLWallRadius               = 0;
      gLLWallGateCount            = 0;
      gLLWallTierAge2Stone        = false;
      gLLWallTriggerAge           = 5;
      gLLWallSegmentLength        = 0;
      gLLWallTowerInterleave      = 0;
      gLLWallSecondaryStrategy    = 3;
      gLLWallVillagerCount        = 0;
      gLLWallForwardBiasFraction  = 0.0;
      gLLWallOuterRingDelta       = 0;
      gLLWallEarlyOutpostCount    = 4;
      gLLWallRepairAggressiveness = 0;
      gLLWallClosurePctTarget     = 0;
      gLLWallNoWaterBuild         = true;
   }
   else if (civKey == "ANWTexians")
   {
      // ANWTexians (ANWTexians): Texas Ranger — pure mobile cavalry, frontier fallback
      gLLWallStrategy             = 5;
      gLLWallRadius               = 0;
      gLLWallGateCount            = 0;
      gLLWallTierAge2Stone        = false;
      gLLWallTriggerAge           = 5;
      gLLWallSegmentLength        = 0;
      gLLWallTowerInterleave      = 0;
      gLLWallSecondaryStrategy    = 3;
      gLLWallVillagerCount        = 0;
      gLLWallForwardBiasFraction  = 0.0;
      gLLWallOuterRingDelta       = 0;
      gLLWallEarlyOutpostCount    = 5;
      gLLWallRepairAggressiveness = 0;
      gLLWallClosurePctTarget     = 0;
      gLLWallNoWaterBuild         = true;
   }
   else
   {
      // Unknown civ — leave defaults from aiHeader.xs.
      llProbe("wall.knobs", "civ=" + civKey + " status=default");
      return;
   }

   // One-shot probe so validators can confirm per-civ knob set reached the engine.
   llProbe("wall.knobs",
      "civ=" + civKey +
      " strategy=" + gLLWallStrategy +
      " r=" + gLLWallRadius +
      " g=" + gLLWallGateCount +
      " stoneA2=" + gLLWallTierAge2Stone +
      " trig=" + gLLWallTriggerAge +
      " segL=" + gLLWallSegmentLength +
      " tow=" + gLLWallTowerInterleave +
      " sec=" + gLLWallSecondaryStrategy +
      " v=" + gLLWallVillagerCount +
      " fwd=" + gLLWallForwardBiasFraction +
      " outer=" + gLLWallOuterRingDelta +
      " outp=" + gLLWallEarlyOutpostCount +
      " rep=" + gLLWallRepairAggressiveness +
      " clo=" + gLLWallClosurePctTarget +
      " noW=" + gLLWallNoWaterBuild);
}
