#!/usr/bin/env python3
"""Bulk picker calibration runner — tries every ANW civ via the verified picker.

For each token in ANW_TO_PICKER_INDEX:
  - Calls lobby_driver.set_civ_by_token_verified(token).
  - Records: target_token, picker_idx tried, OCR'd highlighted-row text,
    matched_on, attempts, actual_token (best guess of what we landed on).

Outputs:
  artifacts/picker_calibration.json     — full per-civ trace
  artifacts/picker_calibration.txt       — short human summary (X/46 verified)

If the calibration discovers a consistent off-by-N drift between
ANW_TO_PICKER_INDEX[token] and the picker_idx where the token was actually
found (via _identify_civ_from_ocr on each attempt's highlighted row), it
emits a corrected mapping at:
  tools/aoe3_automation/anw_civ_picker_map_corrected.py

Usage:
    python3 tools/aoe3_automation/picker_calibration.py
    python3 tools/aoe3_automation/picker_calibration.py --civ ANWBritish
    python3 tools/aoe3_automation/picker_calibration.py --max-attempts 3

The game must already be at the SP Skirmish lobby (see manage_game.py /
launch_retest_mod.sh). Don't run this while another agent is driving the
lobby — it serialises picker access on a single live UI.
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[1]
sys.path.insert(0, str(REPO_ROOT))

from tools.aoe3_automation import lobby_driver  # noqa: E402
from tools.aoe3_automation.anw_civ_picker_map import ANW_TO_PICKER_INDEX  # noqa: E402


def run_one(coords: dict, civ_token: str, ref: dict, *, max_attempts: int) -> dict:
    """Drive one civ-token through the verified-selection path and record."""
    target_idx = ANW_TO_PICKER_INDEX.get(civ_token)
    print(f"\n=== {civ_token} (target_idx={target_idx}) ===", flush=True)
    t0 = time.time()
    res = lobby_driver.set_civ_by_token_verified(
        coords, civ_token, ref, max_attempts=max_attempts,
    )
    elapsed = time.time() - t0
    res["target_idx"] = target_idx
    res["elapsed_s"] = round(elapsed, 1)
    mark = "OK" if res.get("ok") else "FAIL"
    print(
        f"  [{mark}] attempts={res.get('attempts')} "
        f"actual={res.get('actual_token')!r} "
        f"matched_on={res.get('matched_on')!r} "
        f"elapsed={elapsed:.1f}s",
        flush=True,
    )
    last_text = res.get("ocr_text", "")
    if last_text:
        print(f"  ocr: {last_text[:120]!r}", flush=True)
    return res


def detect_offset(results: list[dict]) -> dict:
    """Look for a consistent off-by-N drift in the picker map.

    For every result with an actual_token identified, compute
    delta = ANW_TO_PICKER_INDEX[actual_token] - ANW_TO_PICKER_INDEX[target_token]
    when both are mapped. If the modal delta is non-zero and dominant
    (>50% of identified results), that's a consistent drift we can correct.
    """
    deltas: Counter = Counter()
    samples = 0
    for r in results:
        target = r.get("civ")
        actual = r.get("actual_token")
        if not actual or actual == target:
            continue
        if target not in ANW_TO_PICKER_INDEX or actual not in ANW_TO_PICKER_INDEX:
            continue
        d = ANW_TO_PICKER_INDEX[actual] - ANW_TO_PICKER_INDEX[target]
        deltas[d] += 1
        samples += 1
    if not samples:
        return {"detected": False, "reason": "no identifiable mismatches"}
    most_common = deltas.most_common(1)[0]
    delta, count = most_common
    if count / samples >= 0.5 and abs(delta) > 0:
        return {
            "detected": True,
            "delta": delta,
            "count": count,
            "samples": samples,
            "all_deltas": dict(deltas),
        }
    return {"detected": False, "delta": delta, "count": count,
            "samples": samples, "all_deltas": dict(deltas)}


def write_corrected_map(delta: int, out_path: Path) -> None:
    """Write a corrected picker map shifted by `delta`."""
    lines = [
        '"""Mapping from ANW mod tokens to lobby picker indices.',
        '',
        f'This file was auto-generated by picker_calibration.py with a',
        f'consistent off-by-{delta} drift detected against',
        f'`anw_civ_picker_map.ANW_TO_PICKER_INDEX`. Review before promoting.',
        '"""',
        '',
        '# Auto-corrected from anw_civ_picker_map.ANW_TO_PICKER_INDEX',
        '# (delta = actual_idx - assumed_idx, applied as new = old - delta).',
        '',
        'ANW_TO_PICKER_INDEX = {',
    ]
    items = sorted(ANW_TO_PICKER_INDEX.items(), key=lambda kv: kv[1])
    for token, idx in items:
        new_idx = idx - delta
        lines.append(f'    {token!r}: {new_idx},')
    lines.append('}')
    out_path.write_text("\n".join(lines) + "\n")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--civ", help="single civ token (default: all in ANW_TO_PICKER_INDEX)")
    ap.add_argument("--max-attempts", type=int, default=8,
                    help="max retry attempts per civ (default: 8)")
    ap.add_argument(
        "--reference", type=Path,
        default=REPO_ROOT / "enriched_reference.json",
        help="path to enriched_reference.json",
    )
    ap.add_argument(
        "--out-dir", type=Path,
        default=REPO_ROOT / "artifacts",
        help="directory for picker_calibration.{json,txt}",
    )
    args = ap.parse_args()

    if not args.reference.exists():
        print(f"missing reference: {args.reference}", file=sys.stderr)
        return 1
    ref = json.loads(args.reference.read_text())

    args.out_dir.mkdir(parents=True, exist_ok=True)
    coords = lobby_driver.load_coords()

    if args.civ:
        if args.civ not in ANW_TO_PICKER_INDEX:
            print(f"unknown civ: {args.civ}", file=sys.stderr)
            return 1
        targets = [args.civ]
    else:
        targets = sorted(ANW_TO_PICKER_INDEX.keys())

    results: list[dict] = []
    for token in targets:
        res = run_one(coords, token, ref, max_attempts=args.max_attempts)
        results.append(res)

    verified = [r for r in results if r.get("ok")]
    failed = [r for r in results if not r.get("ok")]

    summary = {
        "total": len(results),
        "verified": len(verified),
        "failed": len(failed),
        "failed_civs": [r["civ"] for r in failed],
        "average_attempts_for_verified": (
            round(sum(r["attempts"] for r in verified) / len(verified), 2)
            if verified else None
        ),
        "drift_analysis": detect_offset(results),
    }

    json_out = args.out_dir / "picker_calibration.json"
    json_out.write_text(json.dumps(
        {"summary": summary, "results": results}, indent=2,
    ))

    text_lines = [
        f"{summary['verified']}/{summary['total']} verified",
    ]
    if failed:
        text_lines.append(f"FAILED ({len(failed)}): " + ", ".join(summary["failed_civs"]))
    drift = summary["drift_analysis"]
    if drift.get("detected"):
        text_lines.append(
            f"DRIFT DETECTED: delta={drift['delta']} "
            f"(in {drift['count']}/{drift['samples']} mismatches)"
        )
    txt_out = args.out_dir / "picker_calibration.txt"
    txt_out.write_text("\n".join(text_lines) + "\n")

    print()
    for line in text_lines:
        print(line)
    print(f"\nwrote {json_out}")
    print(f"wrote {txt_out}")

    if drift.get("detected"):
        corrected = HERE / "anw_civ_picker_map_corrected.py"
        write_corrected_map(drift["delta"], corrected)
        print(f"wrote {corrected} (corrected with delta={drift['delta']})")

    return 0 if not failed else 2


if __name__ == "__main__":
    sys.exit(main())
