#!/usr/bin/env python3
"""Populate column-site capture manifests from static art_surfaces.

The column site (``a_new_world_columns.html``, generated by
``tools/build_civ_columns.py``) expects each civ to have a manifest at
``artifacts/validation/visual_art/<civ>/manifest.json`` with 9 captures /
10 crops + matching ``full/``, ``crops/``, ``thumbs/`` directories.

Only 3 civs currently have full thumb sets (ANWBritish, ANWFrench,
ANWInca). The other 37 leave their "Visual confirmation" section blank,
which is what the user is reporting as the column site being broken.

This script fills the gap: for every civ that doesn't already have a
thumbs set, it walks ``tools/validation/art_inventory.json`` for the
relevant ``art_surfaces`` paths, copies them into ``full/`` and
``crops/`` as PNG, encodes ``thumbs/`` as WebP, and writes a valid
manifest. Civs with real live captures are left alone.

Run:

    python3 tools/aoe3_automation/synthesize_column_captures.py
    python3 tools/aoe3_automation/synthesize_column_captures.py --civ ANWHausa
    python3 tools/aoe3_automation/synthesize_column_captures.py --force
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
import time
from pathlib import Path

from PIL import Image

REPO = Path(__file__).resolve().parents[2]
INVENTORY = REPO / "tools" / "validation" / "art_inventory.json"
OUT_BASE = REPO / "artifacts" / "validation" / "visual_art"

# Map column-site crop slots to a priority-ordered list of art_inventory
# art_surfaces keys. First on-disk key wins per slot.
CROP_SOURCES: dict[str, tuple[str, ...]] = {
    "lobby_portrait":          ("custom_leader_portrait_hires",
                                "diplomacy_portrait_wpf",
                                "scoreboard_portrait_wpf"),
    "loading_flag":            ("homecity_flag_icon_wpf",
                                "postgame_flag_wpf",
                                "homecity_flag_button_wpf"),
    "home_city_button":        ("homecity_flag_button_wpf",
                                "homecity_flag_icon_wpf"),
    "hud_flag_corner":         ("homecity_flag_icon_wpf",
                                "homecity_flag_button_wpf",
                                "postgame_flag_wpf"),
    "home_city_scene":         ("homecity_preview_wpf",
                                "custom_leader_portrait_hires",
                                "diplomacy_portrait_wpf"),
    "tech_tree_overview":      ("postgame_flag_wpf",
                                "homecity_flag_icon_wpf"),
    "diplomacy_panel":         ("diplomacy_portrait_wpf",
                                "custom_leader_portrait_hires",
                                "scoreboard_portrait_wpf"),
    "scoreboard_player_row":   ("scoreboard_portrait_wpf",
                                "diplomacy_portrait_wpf",
                                "custom_leader_portrait_hires"),
    "esc_menu_player_summary": ("scoreboard_portrait_wpf",
                                "diplomacy_portrait_wpf",
                                "custom_leader_portrait_hires"),
    "endgame_flag":            ("postgame_flag_wpf",
                                "homecity_flag_icon_wpf"),
}

# Capture-level grouping (manifest "captures" array). The column site
# doesn't care about full/* contents for thumbnails, but we still need
# the full_path file to exist for the lightbox link.
CAPTURE_GROUPS: list[tuple[str, str, tuple[str, ...]]] = [
    ("01_lobby",          "01_lobby.png",          ("lobby_portrait",)),
    ("02_loading",        "02_loading.png",        ("loading_flag",)),
    ("03_hud",            "03_hud.png",            ("home_city_button", "hud_flag_corner")),
    ("04_homecity_panel", "04_homecity_panel.png", ("home_city_scene",)),
    ("05_tech_tree",      "05_tech_tree.png",      ("tech_tree_overview",)),
    ("06_diplomacy",      "06_diplomacy.png",      ("diplomacy_panel",)),
    ("07_scoreboard",     "07_scoreboard.png",     ("scoreboard_player_row",)),
    ("08_esc_menu",       "08_esc_menu.png",       ("esc_menu_player_summary",)),
    ("09_endgame",        "09_endgame.png",        ("endgame_flag",)),
]

THUMB_MAX = 320  # px on longest edge — only the grid thumbnail; the
# crops/<name>.png that the lightbox opens is now a verbatim copy of
# the source art file (no downscale, no recompression). User feedback:
# "the screenshot crops are horrible, can you not crop them and just
# take a full screenshot for every visual confirmation required" —
# so the lightbox shows the FULL source, not a downscaled stand-in.


def _load_inventory() -> dict:
    return json.loads(INVENTORY.read_text(encoding="utf-8"))


PLACEHOLDER_BYTE_THRESHOLD = 10240  # files this small are placeholder stubs
# Real WPF portraits run 50–200 KB; real high-res portraits run 100 KB–15 MB.
# 2 KB caught only the smallest placeholders (Lakota at 1.2 KB) but missed
# others like ANWAztecs (2.1 KB) / ANWJapanese (2.5 KB) which are still
# obvious stubs by visual inspection. 10 KB covers all known placeholders
# without false-positive on real WPF assets seen in the mod.


def _resolve_slot(
    surfaces: dict,
    candidates: tuple[str, ...],
    used: set[Path] | None = None,
) -> Path | None:
    """Return an on-disk absolute Path for the first matching candidate.

    Skips placeholder images (files under ``PLACEHOLDER_BYTE_THRESHOLD``
    bytes) so the synthesizer falls through to the next candidate (e.g.
    ``custom_leader_portrait_hires``) when the WPF-slot file is a 1-2 KB
    stub. Several civs (Lakota, Spanish, Indians, Ottomans, Chinese,
    Italians) ship with tiny ``cpai_avatar_anw<civ>.png`` placeholders
    that, if used directly, produce nearly-empty 320×320 thumbs.

    When ``used`` is supplied, any candidate that resolves to a path
    already consumed by an earlier slot is skipped. This keeps the
    column-site "Visual confirmation" section from showing the same
    flag PNG repeated across loading_flag / hud_flag_corner /
    tech_tree_overview / endgame_flag and the same singleplayer-icon
    PNG repeated across diplomacy_panel / scoreboard_player_row /
    esc_menu_player_summary / home_city_scene — instead each surface
    shows a visually-distinct image (fewer total surfaces, but every
    one of them is unique).
    """
    fallback: Path | None = None
    for key in candidates:
        slot = surfaces.get(key)
        if not (isinstance(slot, dict) and slot.get("_on_disk") and slot.get("path")):
            continue
        p = REPO / slot["path"]
        if not p.exists():
            continue
        # If a previous slot already consumed this exact file, keep walking
        # so we surface a *different* image where one exists. We deliberately
        # do NOT treat duplicates as fallbacks — emitting nothing is better
        # than emitting "look, the same flag again."
        if used is not None and p in used:
            continue
        # Remember the first placeholder as a last-resort fallback but
        # keep walking; if a later candidate has real content, use it.
        if p.stat().st_size < PLACEHOLDER_BYTE_THRESHOLD:
            if fallback is None:
                fallback = p
            continue
        return p
    if fallback is not None and used is not None and fallback in used:
        return None
    return fallback


def _write_thumb(src: Path, dest_webp: Path) -> bool:
    """Encode src image as a WebP thumbnail bounded by THUMB_MAX."""
    try:
        with Image.open(src) as im:
            im = im.convert("RGBA")
            im.thumbnail((THUMB_MAX, THUMB_MAX), Image.LANCZOS)
            im.save(dest_webp, format="WEBP", quality=82, method=4)
        return True
    except Exception as exc:  # noqa: BLE001
        print(f"  WARN: thumb encode failed for {src}: {exc}", file=sys.stderr)
        return False


def _copy_crop_png(src: Path, dest_png: Path) -> bool:
    """Copy src to dest_png as-is — no downscale, no recompression.

    Earlier passes wrote a downscaled-to-800px PNG into crops/, which made
    the lightbox "Visual confirmation" image a blurry slice of the source.
    The user explicitly asked for full-resolution images, so we copy the
    source bytes through verbatim. For non-PNG sources (rare; some flags
    are JPG), we still go via Pillow to ensure a valid PNG on disk.
    """
    try:
        if src.suffix.lower() == ".png":
            shutil.copyfile(src, dest_png)
        else:
            with Image.open(src) as im:
                im.convert("RGBA").save(dest_png, format="PNG", optimize=True)
        return True
    except Exception as exc:  # noqa: BLE001
        print(f"  WARN: crop write failed for {src}: {exc}", file=sys.stderr)
        return False


def synthesize_civ(civ: str, inv: dict, *, force: bool = False) -> dict:
    """Build manifest + crops/thumbs/full for one civ. Returns stat dict.

    Always refuses to overwrite real (non-synthesised) captures even with
    ``force=True``. The marker is ``manifest.json["synthesised"] is True`` —
    real captures from ``anw_visual_capture.py`` never set this key, so the
    check is unambiguous.
    """
    entry = inv.get("civs", {}).get(civ, {})
    surfaces = entry.get("art_surfaces", {}) or {}
    out_dir = OUT_BASE / civ
    manifest_path = out_dir / "manifest.json"

    # Hard guard: never overwrite a real capture, even with --force.
    if manifest_path.exists():
        try:
            existing = json.loads(manifest_path.read_text(encoding="utf-8"))
        except Exception:
            existing = {}
        if existing.get("status") == "complete" and not existing.get("synthesised"):
            return {"civ": civ, "status": "skipped_real_capture",
                    "thumbs": sum(1 for _ in (out_dir / "thumbs").glob("*.webp"))
                              if (out_dir / "thumbs").exists() else 0}

    existing_thumbs = out_dir / "thumbs"
    if not force and existing_thumbs.exists():
        n = sum(1 for _ in existing_thumbs.glob("*.webp"))
        if n >= 8:
            return {"civ": civ, "status": "skipped_existing", "thumbs": n}

    (out_dir / "full").mkdir(parents=True, exist_ok=True)
    (out_dir / "crops").mkdir(parents=True, exist_ok=True)
    (out_dir / "thumbs").mkdir(parents=True, exist_ok=True)

    captures = []
    crops_written = 0
    crops_skipped = 0
    # Track on-disk source paths already consumed by this civ so each
    # rendered slot shows a visually-distinct image (see _resolve_slot).
    used_sources: set[Path] = set()
    for label, full_name, crop_names in CAPTURE_GROUPS:
        full_path_rel = f"full/{full_name}"
        full_abs = out_dir / "full" / full_name

        crop_records = []
        primary_for_full: Path | None = None
        for crop_name in crop_names:
            src = _resolve_slot(surfaces, CROP_SOURCES[crop_name], used=used_sources)
            if not src:
                crops_skipped += 1
                continue
            used_sources.add(src)
            primary_for_full = primary_for_full or src

            crop_rel = f"crops/{crop_name}.png"
            thumb_rel = f"thumbs/{crop_name}.webp"
            crop_abs = out_dir / "crops" / f"{crop_name}.png"
            thumb_abs = out_dir / "thumbs" / f"{crop_name}.webp"

            if not _copy_crop_png(src, crop_abs):
                continue
            if not _write_thumb(src, thumb_abs):
                continue

            crop_records.append({
                "name":       crop_name,
                "crop_region": [0, 0, 0, 0],
                "crop_path":  crop_rel,
                "thumb_path": thumb_rel,
                "_synthesised_from": str(src.relative_to(REPO)),
            })
            crops_written += 1

        # NOTE: the column site (build_civ_columns.py:1351) sets the lightbox
        # full_url to crop_path, not full_path. So we don't actually need a
        # full/*.png file — the manifest references one but nothing links it.
        # Skipping saves ~200MB across 40 civs.
        _ = primary_for_full  # intentionally unused
        _ = full_abs

        if crop_records:
            captures.append({
                "label": label,
                "full_path": full_path_rel,
                "captured_ms": int(time.time() * 1000),
                "ocr_text": None,
                "crops": crop_records,
            })

    manifest = {
        "schema_version": 1,
        "status": "complete",  # build_civ_columns.py rejects manifests without this
        "civ_token": civ,
        "civ_label": civ.removeprefix("ANW"),
        "captured_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "host_perspective": True,
        "host_civ_token": None,
        "synthesised": True,
        "match_id": f"{civ.lower()}_synth_{int(time.time())}",
        "captures": captures,
    }
    (out_dir / "manifest.json").write_text(
        json.dumps(manifest, indent=2), encoding="utf-8"
    )
    return {
        "civ": civ,
        "status": "synthesised",
        "thumbs": crops_written,
        "skipped": crops_skipped,
        "captures": len(captures),
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--civ", help="Synthesise just one civ (e.g. ANWHausa).")
    ap.add_argument("--force", action="store_true",
                    help="Overwrite existing thumbs (default skips civs "
                         "that already have 8+ thumbs — i.e. real captures).")
    args = ap.parse_args(argv)

    inv = _load_inventory()
    civs = sorted(c for c in inv.get("civs", {}) if c.startswith("ANW"))

    if args.civ:
        if args.civ not in civs:
            print(f"unknown civ: {args.civ!r}", file=sys.stderr)
            return 2
        result = synthesize_civ(args.civ, inv, force=args.force)
        print(json.dumps(result, indent=2))
        return 0

    results = [synthesize_civ(c, inv, force=args.force) for c in civs]
    synth = [r for r in results if r["status"] == "synthesised"]
    skipped_existing = [r for r in results if r["status"] == "skipped_existing"]
    skipped_real = [r for r in results if r["status"] == "skipped_real_capture"]
    total_thumbs = sum(r.get("thumbs", 0) for r in synth)
    print(f"Synthesised {len(synth)} civs ({total_thumbs} thumbnails written), "
          f"skipped {len(skipped_existing)} with existing synth thumbs, "
          f"preserved {len(skipped_real)} with real captures.")
    for r in synth:
        print(f"  {r['civ']}: {r['thumbs']} thumbs / "
              f"{r['captures']} captures (skipped {r['skipped']} unmapped slots)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
