#!/usr/bin/env python3
"""
build_civ_columns.py — Generate a_new_world_columns.html
Horizontal-scroll civ review page: one column per nation, 100vh height, no vertical scroll.

Run from any directory; all paths are resolved relative to this script's location.
"""
import os, json, re, html as html_module
import xml.etree.ElementTree as ET

# ── Paths ──────────────────────────────────────────────────────────────────────
SCRIPT_DIR   = os.path.dirname(os.path.abspath(__file__))
MOD_ROOT     = os.path.dirname(SCRIPT_DIR)
DATA_DIR     = os.path.join(MOD_ROOT, "data")
GAME_DIR     = os.path.join(MOD_ROOT, "game")
RESOURCES    = os.path.join(MOD_ROOT, "resources")
OUTPUT_HTML  = os.path.join(MOD_ROOT, "a_new_world_columns.html")

# Capture artifacts root (host-perspective manifests live here)
VISUAL_ART_DIR = os.path.join(MOD_ROOT, "artifacts", "validation", "visual_art")

# URL base used in the generated HTML — maps to the staging step in pages-deploy.yml:
#   cp -r artifacts/validation/visual_art _site/artifacts/visual_art
VISUAL_ART_URL_BASE = "artifacts/visual_art"

# Manifest schema version this generator understands
MANIFEST_SCHEMA_VERSION = 1

# Vanilla asset inventory summary (per-civ-stem bucket counts derived from
# the AoE3DE .bar archives). Generated by tools/bar_inventory.py + the small
# digest script that lives in the commit message of the column rebuild.
# Each entry: stem -> {bucket: count, _aliases: [vanilla_tokens], _total: int}.
_VANILLA_SUMMARY_PATH = os.path.join(SCRIPT_DIR, "vanilla_asset_summary.json")
try:
    with open(_VANILLA_SUMMARY_PATH, "r", encoding="utf-8") as _f:
        VANILLA_SUMMARY = json.load(_f)
except Exception:
    VANILLA_SUMMARY = {}

# Human-readable surface names for crop names
CROP_SURFACE_LABELS = {
    "lobby_portrait":          "Lobby portrait",
    "loading_flag":            "Loading flag",
    "home_city_button":        "Home City button",
    "hud_flag_corner":         "HUD flag corner",
    "home_city_scene":         "Home City scene",
    "tech_tree_overview":      "Tech tree overview",
    "diplomacy_panel":         "Diplomacy panel",
    "scoreboard_player_row":   "Scoreboard row",
    "esc_menu_player_summary": "ESC menu summary",
    "endgame_flag":            "Endgame flag",
    "diplomacy_ally_portrait": "Ally portrait",
}

def surface_label(crop_name):
    """Return a human-readable label for a crop/surface name."""
    if crop_name in CROP_SURFACE_LABELS:
        return CROP_SURFACE_LABELS[crop_name]
    # Fallback: title-case with underscores replaced by spaces
    return crop_name.replace("_", " ").title()


def capture_dir_key(civ_token):
    """
    Return the directory name used under artifacts/validation/visual_art/ for a civ.

    The capture pipeline uses ANW-prefixed tokens (e.g. ANWBritish) as directory
    names.  The civmods/playercolors data uses the base tokens (e.g. British).
    blurb_key() already contains the canonical ANW mapping, so reuse it.
    """
    return blurb_key(civ_token)


def load_capture_manifest(civ_token, ally=False):
    """
    Load and validate a capture manifest for a civ.

    For host perspective:  artifacts/validation/visual_art/<dir_key>/manifest.json
    For ally perspective:  artifacts/validation/visual_art/allies/<dir_key>/manifest.json

    Returns the parsed dict if schema_version==1 and status=="complete", else None.
    """
    dir_key = capture_dir_key(civ_token)
    if ally:
        manifest_path = os.path.join(VISUAL_ART_DIR, "allies", dir_key, "manifest.json")
    else:
        manifest_path = os.path.join(VISUAL_ART_DIR, dir_key, "manifest.json")

    if not os.path.exists(manifest_path):
        return None

    try:
        with open(manifest_path, encoding="utf-8") as f:
            data = json.load(f)
    except (json.JSONDecodeError, OSError):
        return None

    if data.get("schema_version") != MANIFEST_SCHEMA_VERSION:
        return None
    if data.get("status") != "complete":
        return None

    return data

# ── Load data sources ──────────────────────────────────────────────────────────
def load_strings():
    path = os.path.join(DATA_DIR, "strings", "english", "stringmods.xml")
    tree = ET.parse(path)
    strings = {}
    for elem in tree.getroot().iter("String"):
        loc_id = elem.get("_locID")
        if loc_id and elem.text:
            strings[loc_id] = elem.text.strip()
    return strings

def load_civmods():
    path = os.path.join(DATA_DIR, "civmods.xml")
    tree = ET.parse(path)
    civs = {}
    for civ in tree.getroot().findall(".//civ"):
        name = civ.findtext("name")
        if name:
            civs[name] = civ
    return civs

def load_playercolors():
    path = os.path.join(DATA_DIR, "playercolors.xml")
    tree = ET.parse(path)
    colors = {}
    for c in tree.getroot().findall(".//Color"):
        civ = c.get("civ")
        if civ:
            colors[civ] = {
                "r": int(c.get("r", 80)),
                "g": int(c.get("g", 80)),
                "b": int(c.get("b", 80)),
                "leader": c.get("leader", ""),
            }
    return colors

def load_homecity(filename):
    path = os.path.join(DATA_DIR, filename)
    if not os.path.exists(path):
        return None
    tree = ET.parse(path)
    root = tree.getroot()
    data = {}
    for child in root:
        tag = child.tag
        if tag not in data:
            data[tag] = child.text.strip() if child.text else ""
    # Cards by age
    cards_by_age = {}
    for card in root.findall(".//cards/card"):
        age = card.findtext("age") or "0"
        name_elem = card.findtext("name") or ""
        age_key = str(int(float(age))) if age.strip() else "0"
        cards_by_age.setdefault(age_key, []).append(name_elem)
    data["cards_by_age"] = cards_by_age
    return data

def load_blurbs():
    path = os.path.join(DATA_DIR, "anw_civ_blurbs.json")
    with open(path) as f:
        return json.load(f)

def load_playstyle_spec():
    path = os.path.join(MOD_ROOT, "playstyle_spec.json")
    if not os.path.exists(path):
        return {}
    with open(path) as f:
        spec = json.load(f)
    # The spec has civs keyed by display label
    civs_raw = spec.get("civs", {})
    # Build mapping: civ_label -> data
    result = {}
    for key, val in civs_raw.items():
        if isinstance(val, dict):
            civ_label = val.get("civ_label", "")
            result[key] = val
    return civs_raw

def load_decks():
    path = os.path.join(DATA_DIR, "decks_anw.json")
    with open(path) as f:
        return json.load(f)

def load_cards():
    path = os.path.join(DATA_DIR, "cards.json")
    with open(path) as f:
        return json.load(f)

def load_personality(civ_name):
    """Load rushboom value from .personality file."""
    # Normalise civ_name to filename: remove prefix ANW/DE/XP, lowercase
    lower = civ_name.lower()
    for prefix in ("anw", "de", "xp"):
        if lower.startswith(prefix):
            lower = lower[len(prefix):]
            break
    # Try with anw prefix first
    candidates = [
        f"anw{lower}.personality",
        f"{lower}.personality",
    ]
    for fname in candidates:
        path = os.path.join(GAME_DIR, "ai", fname)
        if os.path.exists(path):
            with open(path) as f:
                content = f.read()
            m = re.search(r"<rushboom>(\d+)</rushboom>", content)
            if m:
                val = int(m.group(1))
                label = {0: "Boom", 1: "Rush", 2: "Balanced"}.get(val, str(val))
                return label, fname
            return "?", fname
    return "?", None

def personality_path_str(civ_name):
    lower = civ_name.lower()
    for prefix in ("anw", "de", "xp"):
        if lower.startswith(prefix):
            lower = lower[len(prefix):]
            break
    fname = f"anw{lower}.personality"
    path = os.path.join(GAME_DIR, "ai", fname)
    if os.path.exists(path):
        return f"game/ai/{fname}"
    return f"game/ai/anw{lower}.personality (missing)"

def resolve_img(rel_path):
    """Return (rel_path_for_html, exists) for a resource path."""
    if not rel_path:
        return None, False
    # Normalise backslashes
    rel_path = rel_path.replace("\\", "/")
    # Possible base locations
    candidates = [
        os.path.join(MOD_ROOT, rel_path),
        os.path.join(MOD_ROOT, "resources", rel_path),
        os.path.join(MOD_ROOT, "data", rel_path),
    ]
    for c in candidates:
        if os.path.exists(c):
            # Return path relative to MOD_ROOT (= same dir as output HTML)
            rel = os.path.relpath(c, MOD_ROOT)
            return rel.replace("\\", "/"), True
    return rel_path, False

def img_tag(path, alt="", size=50):
    rel, exists = resolve_img(path)
    if exists:
        return (
            f'<img loading="lazy" src="{html_module.escape(rel)}" '
            f'alt="{html_module.escape(alt)}" '
            f'title="{html_module.escape(rel)}" '
            f'style="width:{size}px;height:{size}px;object-fit:contain;'
            f'border:1px solid rgba(255,255,255,0.2);border-radius:2px;background:#0004;">'
        ), True
    else:
        return (
            f'<span class="path-missing" title="{html_module.escape(path)}">'
            f'<code>{html_module.escape(rel)}</code></span>'
        ), False

# ── CIV key normalisation ──────────────────────────────────────────────────────
def blurb_key(civ_token):
    """Map civmods token to blurbs key (ANWXxx style)."""
    mappings = {
        "French":       "ANWFrench",
        "British":      "ANWBritish",
        "Germans":      "ANWGermans",
        "Russians":     "ANWRussians",
        "Spanish":      "ANWSpanish",
        "Ottomans":     "ANWOttomans",
        "Portuguese":   "ANWPortuguese",
        "Dutch":        "ANWDutch",
        "DEItalians":   "ANWItalians",
        "DEMaltese":    "ANWMaltese",
        "DESwedish":    "ANWSwedes",
        "Chinese":      "ANWChinese",
        "Japanese":     "ANWJapanese",
        "Indians":      "ANWIndians",
        "XPAztec":      "ANWAztecs",
        "XPIroquois":   "ANWHaudenosaunee",
        "DEInca":       "ANWInca",
        "XPSioux":      "ANWLakota",
        "DEAmericans":  "ANWUSA",
        "DEMexicans":   "ANWMexicans",
        "DEEthiopians": "ANWEthiopians",
        "DEHausa":      "ANWHausa",
    }
    if civ_token in mappings:
        return mappings[civ_token]
    return civ_token  # ANW* tokens match directly

def deck_key(civ_token):
    """Map civmods token to decks_anw.json key."""
    # Most ANW civs match directly; base civs also match directly
    return civ_token

# ── Playstyle spec lookup ──────────────────────────────────────────────────────
def find_spec_entry(civ_token, spec):
    """Try to find a matching playstyle spec entry for a civ token."""
    # The spec uses human-readable keys like 'Hungarians Kossuth Revolution'
    # Try to match by civ_label in the values
    b_key = blurb_key(civ_token)
    # Strip ANW prefix and convert to base name
    base = b_key[3:] if b_key.startswith("ANW") else b_key
    base_lower = base.lower()
    for key, val in spec.items():
        if not isinstance(val, dict):
            continue
        civ_label = val.get("civ_label", "")
        if civ_label.lower() == base_lower:
            return val, key
        if base_lower in key.lower():
            return val, key
    return None, None

# ── Colour helpers ─────────────────────────────────────────────────────────────
def luminance(r, g, b):
    def c(x):
        x /= 255
        return x / 12.92 if x <= 0.03928 else ((x + 0.055) / 1.055) ** 2.4
    return 0.2126 * c(r) + 0.7152 * c(g) + 0.0722 * c(b)

def text_color(r, g, b):
    return "#fff" if luminance(r, g, b) < 0.35 else "#111"

def bg_style(r, g, b):
    return (
        f"background:linear-gradient(160deg,"
        f"rgb({r},{g},{b}) 0%,"
        f"rgb({max(r-30,0)},{max(g-30,0)},{max(b-30,0)}) 100%);"
    )

# ── Section renderers ──────────────────────────────────────────────────────────
def render_text_section(civ_token, civ_el, strings, hc, blurbs, spec, decks, cards, colors):
    bk = blurb_key(civ_token)
    blurb = blurbs.get(bk, {})
    spec_entry, spec_key = find_spec_entry(civ_token, spec)

    # Display name
    display_id = civ_el.findtext("displaynameid") or ""
    display_name = strings.get(display_id, civ_token)

    # Stats id
    statsid = civ_el.findtext("statsid") or ""

    # Culture
    culture = civ_el.findtext("culture") or ""

    # Allied/Unallied IDs
    allied_id    = civ_el.findtext("alliedid") or ""
    unallied_id  = civ_el.findtext("unalliedid") or ""
    allied_other = civ_el.findtext("alliedotherid") or ""

    # Leader name from homecity
    leader_name = ""
    if hc:
        hero_name_raw = hc.get("heroname", "")
        if hero_name_raw.startswith("$$") and hero_name_raw.endswith("$$"):
            loc_id = hero_name_raw[2:-2]
            leader_name = strings.get(loc_id, hero_name_raw)
        else:
            leader_name = hero_name_raw

    # Leader from playercolors
    color_entry = colors.get(civ_token, {})
    pc_leader = color_entry.get("leader", "")

    # Doctrine
    doctrine_label   = spec_entry.get("doctrine_label",   "") if spec_entry else ""
    doctrine_summary = spec_entry.get("doctrine_summary", "") if spec_entry else ""

    # Blurb
    civ_bonus = blurb.get("civ_bonus", "") if blurb else ""
    playstyle  = blurb.get("playstyle", "") if blurb else ""
    age_up     = blurb.get("age_up", "") if blurb else ""

    # Unique units
    unique_units = []
    if blurb and blurb.get("unique_units"):
        unique_units = blurb["unique_units"][:5]

    # Cards by age
    dk = deck_key(civ_token)
    deck_data = decks.get(dk, {})
    cards_html_parts = []
    for age in ["0", "1", "2", "3", "4"]:
        age_cards = deck_data.get(age, [])
        if not age_cards:
            continue
        card_html_items = []
        for card_id in age_cards:
            card_info = cards.get(card_id, {})
            card_name = card_info.get("name") or card_id
            card_desc = card_info.get("desc") or ""
            card_icon = card_info.get("icon") or ""
            tooltip = card_name + (f"\n\n{card_desc}" if card_desc else "")
            tooltip_attr = html_module.escape(tooltip[:400], quote=True)
            icon_rendered = False
            if card_icon:
                icon_rel = f"resources/images/icons/cards/{card_icon}"
                if os.path.exists(os.path.join(MOD_ROOT, icon_rel)):
                    card_html_items.append(
                        f'<img class="card-img" loading="lazy" '
                        f'src="{html_module.escape(icon_rel)}" '
                        f'alt="{html_module.escape(card_name)}" '
                        f'title="{tooltip_attr}">'
                    )
                    icon_rendered = True
            if not icon_rendered:
                card_html_items.append(
                    f'<span class="card-text" title="{tooltip_attr}">'
                    f'{html_module.escape(card_name)}</span>'
                )
        age_label = {
            "0": "Discovery", "1": "Colonial", "2": "Fortress",
            "3": "Industrial", "4": "Imperial"
        }.get(age, f"Age {age}")
        cards_html_parts.append(
            f'<div class="age-row age-{age}"><span class="age-lbl">{age_label}</span>'
            f'<span class="age-cards">{"".join(card_html_items)}</span></div>'
        )

    # Rush/boom
    rushboom, personality_fname = load_personality(civ_token)

    # Personality path
    pers_path = personality_path_str(civ_token)

    rows = []
    def row(label, value, mono=False):
        if not value:
            value = '<span class="empty">—</span>'
        cls = "mono" if mono else ""
        rows.append(
            f'<tr><td class="lbl">{html_module.escape(label)}</td>'
            f'<td class="{cls}">{value}</td></tr>'
        )

    row("Display name", f'<strong>{html_module.escape(display_name)}</strong>')
    row("Civ token",    f'<code>{html_module.escape(civ_token)}</code>', mono=True)
    row("Stats ID",     html_module.escape(statsid))
    row("Culture",      html_module.escape(culture))
    row("Leader (HC)",  html_module.escape(leader_name) if leader_name else "")
    if pc_leader and pc_leader != leader_name:
        row("Leader (PC)", html_module.escape(pc_leader))
    row("Allied ID",   html_module.escape(allied_id))
    row("Unallied ID", html_module.escape(unallied_id))
    row("Other ID",    html_module.escape(allied_other))
    row("AI Rush/Boom", html_module.escape(rushboom))
    row("Doctrine",    html_module.escape(doctrine_label))
    row("Doctrine sum.", html_module.escape(doctrine_summary))

    if civ_bonus:
        rows.append(
            f'<tr><td class="lbl">Civ bonus</td>'
            f'<td class="blurb-cell">{html_module.escape(civ_bonus)}</td></tr>'
        )
    if playstyle:
        rows.append(
            f'<tr><td class="lbl">Playstyle</td>'
            f'<td class="blurb-cell">{html_module.escape(playstyle[:160])}</td></tr>'
        )
    if age_up:
        row("Age up", html_module.escape(age_up))
    if unique_units:
        row("Unique units", html_module.escape(", ".join(unique_units)))

    rows_html = "\n".join(rows)
    cards_html = "\n".join(cards_html_parts) if cards_html_parts else '<span class="empty">No deck data</span>'

    return f"""
<div class="text-section">
  <table class="info-table">
    <tbody>{rows_html}</tbody>
  </table>
  <div class="cards-section">
    <div class="section-label">Cards</div>
    {cards_html}
  </div>
</div>
"""

def get_civ_stem(civ_token):
    """Strip prefix to get the short stem used in avatar/flag filenames.
    e.g. ANWBritish→british, DEItalians→italians, XPAztec→aztec."""
    lower = civ_token.lower()
    for prefix in ("anw", "de", "xp"):
        if lower.startswith(prefix):
            return lower[len(prefix):]
    return lower


# Map a file-stem (returned by get_civ_stem) to the mod XML / vanilla-summary
# stem key — needed because some XP/DE tokens strip to historic-vanilla names
# (XPAztec→aztec, XPIroquois→iroquois) while the JSON summary keys use the
# mod's renamed plural form (aztecs, haudenosaunee).
_VANILLA_STEM_ALIAS = {
    "aztec":     "aztecs",
    "iroquois":  "haudenosaunee",
    "sioux":     "lakota",
    "americans": "usa",
    "swedish":   "swedes",
}


def vanilla_summary_stem(civ_token):
    """Stem key to look up in VANILLA_SUMMARY for this civ token."""
    s = get_civ_stem(civ_token)
    return _VANILLA_STEM_ALIAS.get(s, s)

def find_leader_portraits(civ_stem):
    """List per-leader avatar files for this civ_stem.
    Returns [{leader, png_rel, ddt_rel, has_png, has_ddt}, ...]."""
    portrait_dir = os.path.join(MOD_ROOT, "resources/images/icons/singleplayer")
    out = []
    if not os.path.isdir(portrait_dir):
        return out
    prefix = f"cpai_avatar_{civ_stem}_"
    for fn in sorted(os.listdir(portrait_dir)):
        if fn.startswith(prefix) and fn.endswith(".png"):
            leader = fn[len(prefix):-4]
            png_rel = f"resources/images/icons/singleplayer/{fn}"
            ddt_rel = f"art/ui/singleplayer/cpai_avatar_{civ_stem}_{leader}.ddt"
            out.append({
                "leader":  leader,
                "png_rel": png_rel,
                "ddt_rel": ddt_rel,
                "has_png": True,
                "has_ddt": os.path.exists(os.path.join(MOD_ROOT, ddt_rel)),
            })
    return out

def render_art_section(civ_token, civ_el, hc, strings):
    """Comprehensive art-coverage audit. Uses British as the reference surface set.
    Each row is ✓ (present + thumb when previewable) / ✗ (referenced but missing on
    disk) / — (not referenced in XML)."""
    stem = get_civ_stem(civ_token)
    present = 0
    missing = 0
    parts = []

    def thumb(rel):
        return (
            f'<img class="cov-thumb" loading="lazy" '
            f'src="{html_module.escape(rel)}" alt="">'
        )

    def cov_row(label, key_or_path, *, expect_file=None, kind="ui"):
        """One coverage row.
        - key_or_path : XML-declared path, or "" for "not referenced"
        - expect_file : optional fallback path to test if no XML ref (used for
                         default avatar PNG/DDT which aren't in civmods.xml)"""
        nonlocal present, missing
        path = key_or_path or ""
        if path:
            rel, exists = resolve_img(path)
        elif expect_file:
            full = os.path.join(MOD_ROOT, expect_file)
            exists = os.path.exists(full)
            rel = expect_file if exists else expect_file
        else:
            parts.append(
                f'<div class="cov-row"><span class="cov-lbl">{html_module.escape(label)}</span>'
                f'<span class="cov-na">—</span>'
                f'<code class="cov-path">(no XML ref)</code></div>'
            )
            return

        basename = os.path.basename(rel)
        if exists:
            present += 1
            previewable = rel.lower().endswith((".png", ".jpg", ".webp"))
            mark = '<span class="cov-ok">✓</span>'
            thumb_html = thumb(rel) if previewable else ""
            parts.append(
                f'<div class="cov-row"><span class="cov-lbl">{html_module.escape(label)}</span>'
                f'{mark}{thumb_html}'
                f'<code class="cov-path" title="{html_module.escape(rel)}">{html_module.escape(basename)}</code></div>'
            )
        else:
            missing += 1
            mark = '<span class="cov-bad">✗</span>'
            parts.append(
                f'<div class="cov-row"><span class="cov-lbl">{html_module.escape(label)}</span>'
                f'{mark}'
                f'<code class="cov-path cov-path-missing" title="missing: {html_module.escape(path or expect_file or "")}">'
                f'{html_module.escape(basename)}</code></div>'
            )

    # ── Section A: WPF/PNG surfaces from civmods.xml ─────────────────────────
    parts.append('<div class="cov-group-lbl">UI surfaces (civmods.xml)</div>')
    cov_row("HC flag (large)",  civ_el.findtext("homecityflagiconwpf") or "")
    cov_row("HC flag button",   civ_el.findtext("homecityflagbuttonwpf") or "")
    cov_row("HC preview",       civ_el.findtext("homecitypreviewwpf") or "")
    cov_row("PG flag",          civ_el.findtext("postgameflagiconwpf") or "")
    mm_el = civ_el.find(".//smallportraittexturewpf")
    mm_path = (mm_el.text or "").strip() if mm_el is not None else ""
    cov_row("Matchmaking",      mm_path)

    # ── Section B: Default avatar (PNG + compiled DDT) ───────────────────────
    parts.append('<div class="cov-group-lbl">Default avatar</div>')
    default_png = f"resources/images/icons/singleplayer/cpai_avatar_{stem}.png"
    default_ddt = f"art/ui/singleplayer/cpai_avatar_{stem}.ddt"
    cov_row("Default avatar PNG", "", expect_file=default_png)
    cov_row("Default avatar DDT", "", expect_file=default_ddt)

    # ── Section C: Per-leader portraits ──────────────────────────────────────
    leaders = find_leader_portraits(stem)
    parts.append(
        f'<div class="cov-group-lbl">Per-leader portraits ({len(leaders)})</div>'
    )
    if not leaders:
        parts.append(
            '<div class="cov-row cov-leader"><span class="cov-lbl">(none found)</span></div>'
        )
    for L in leaders:
        present += 1  # PNG counted
        if L["has_ddt"]:
            present += 1
            ddt_mark = '<span class="cov-ok" title="DDT present">DDT ✓</span>'
        else:
            missing += 1
            ddt_mark = (
                '<span class="cov-bad" title="missing: '
                + html_module.escape(L["ddt_rel"]) + '">DDT ✗</span>'
            )
        parts.append(
            f'<div class="cov-row cov-leader">'
            f'<span class="cov-lbl">{html_module.escape(L["leader"])}</span>'
            f'<span class="cov-ok">✓</span>'
            f'{thumb(L["png_rel"])}'
            f'<code class="cov-path">cpai_avatar_{html_module.escape(stem)}_{html_module.escape(L["leader"])}.png</code>'
            f'{ddt_mark}</div>'
        )

    # ── Section D: HC scene composition (declared in anwhomecity<civ>.xml) ──
    # Engine-managed asset files, but the *declaration* is mod-managed.
    # British is the reference: 10 surfaces all declared.
    parts.append('<div class="cov-group-lbl">HC scene declaration</div>')
    scene_surfaces = [
        ("Scene visual",     "visual"),
        ("Water visual",     "watervisual"),
        ("Background visual","backgroundvisual"),
        ("Path data (.gr2)", "pathdata"),
        ("Camera (.cam)",    "camera"),
        ("Widescreen cam",   "widescreencamera"),
        ("Ambient sounds",   "ambientsounds"),
        ("Light set",        "lightset"),
        ("Water type",       "watertype"),
        ("XSAI personality", "xsai"),
    ]
    for label, key in scene_surfaces:
        val = (hc or {}).get(key, "").strip()
        if val:
            present += 1
            parts.append(
                f'<div class="cov-row"><span class="cov-lbl">{html_module.escape(label)}</span>'
                f'<span class="cov-ok" title="declared in homecity XML">✓</span>'
                f'<code class="cov-path" title="{html_module.escape(val)}">{html_module.escape(val)}</code></div>'
            )
        else:
            missing += 1
            parts.append(
                f'<div class="cov-row"><span class="cov-lbl">{html_module.escape(label)}</span>'
                f'<span class="cov-bad" title="not declared in homecity XML">✗</span>'
                f'<code class="cov-path cov-path-missing">(undeclared)</code></div>'
            )

    # ── Section E: HC buildings ────────────────────────────────────────────
    # Count <homecitybuilding> blocks in the home city XML. British has 7.
    hc_file = civ_el.findtext("homecityfilename") or ""
    hc_buildings = []
    if hc_file:
        hc_path = os.path.join(DATA_DIR, hc_file)
        if os.path.exists(hc_path):
            try:
                hc_tree = ET.parse(hc_path)
                hc_root = hc_tree.getroot()
                # Direct children of <homecity> tagged <building>
                for b in hc_root.findall("./building"):
                    name = b.findtext("name") or "?"
                    portrait = b.findtext("portrait") or ""
                    hc_buildings.append({"name": name, "portrait": portrait})
            except ET.ParseError:
                pass
    parts.append(
        f'<div class="cov-group-lbl">HC buildings ({len(hc_buildings)})</div>'
    )
    if not hc_buildings:
        parts.append(
            '<div class="cov-row"><span class="cov-lbl">(none parsed)</span></div>'
        )
    for b in hc_buildings:
        present += 1
        parts.append(
            f'<div class="cov-row cov-leader">'
            f'<span class="cov-lbl">{html_module.escape(b["name"])}</span>'
            f'<span class="cov-ok">✓</span>'
            f'<code class="cov-path" title="{html_module.escape(b["portrait"])}">'
            f'{html_module.escape(os.path.basename(b["portrait"])) if b["portrait"] else "(no portrait)"}'
            f'</code></div>'
        )

    # ── Section F: AI personality ─────────────────────────────────────────
    parts.append('<div class="cov-group-lbl">AI personality</div>')
    personality_rel = f"game/ai/anw{stem}.personality"
    if os.path.exists(os.path.join(MOD_ROOT, personality_rel)):
        present += 1
        parts.append(
            f'<div class="cov-row"><span class="cov-lbl">Personality</span>'
            f'<span class="cov-ok">✓</span>'
            f'<code class="cov-path">{html_module.escape(os.path.basename(personality_rel))}</code></div>'
        )
    else:
        missing += 1
        parts.append(
            f'<div class="cov-row"><span class="cov-lbl">Personality</span>'
            f'<span class="cov-bad">✗</span>'
            f'<code class="cov-path cov-path-missing">{html_module.escape(os.path.basename(personality_rel))}</code></div>'
        )

    # ── Section G: Card icons (custom mod-art per civ) ────────────────────
    # Scan resources/images/icons/cards/ for files containing the civ stem.
    card_icons = []
    card_dir = os.path.join(MOD_ROOT, "resources/images/icons/cards")
    if os.path.isdir(card_dir):
        stem_re = re.compile(rf"(?:^|[_-]){re.escape(stem)}(?:[_.-]|$)", re.IGNORECASE)
        for fn in sorted(os.listdir(card_dir)):
            if fn.endswith(".png") and stem_re.search(fn[:-4]):
                card_icons.append(fn)
    parts.append(
        f'<div class="cov-group-lbl">Custom card icons ({len(card_icons)})</div>'
    )
    if not card_icons:
        parts.append(
            '<div class="cov-row"><span class="cov-lbl">(none)</span></div>'
        )
    for fn in card_icons[:12]:  # cap so the column stays scannable
        present += 1
        rel = f"resources/images/icons/cards/{fn}"
        parts.append(
            f'<div class="cov-row cov-leader">'
            f'<span class="cov-lbl">{html_module.escape(fn[:-4])}</span>'
            f'<span class="cov-ok">✓</span>'
            f'{thumb(rel)}</div>'
        )
    if len(card_icons) > 12:
        parts.append(
            f'<div class="cov-row"><span class="cov-lbl">… +{len(card_icons)-12} more</span></div>'
        )

    # ── Section H: Vanilla asset parity (vs. British reference) ────────────
    # Pulled from VANILLA_SUMMARY (digest of the 116k-entry .bar inventory).
    # British is the reference; any new ANW civ with 0 entries needs custom art.
    parts.append(
        '<div class="cov-group-lbl" title="vanilla AoE3 DE .bar inventory match counts; British is the reference">'
        'Vanilla asset parity (vs. British)</div>'
    )
    ref = VANILLA_SUMMARY.get("british", {})
    summary_key = vanilla_summary_stem(civ_token)
    cur = VANILLA_SUMMARY.get(summary_key, {})
    aliases = cur.get("_aliases", [summary_key]) if cur else [summary_key]
    if not VANILLA_SUMMARY:
        parts.append(
            '<div class="cov-row"><span class="cov-lbl">(summary unavailable)</span></div>'
        )
    else:
        # Show alias used so we know what vanilla-name we matched
        alias_str = ", ".join(aliases)
        parts.append(
            f'<div class="cov-row"><span class="cov-lbl">Vanilla token(s)</span>'
            f'<code class="cov-path">{html_module.escape(alias_str)}</code></div>'
        )

        def parity_row(label, key, ref_dict, cur_dict):
            r = ref_dict.get(key, 0)
            c = cur_dict.get(key, 0) if cur_dict else 0
            if key == "_ui_all":
                r = sum(ref_dict.get(k, 0) for k in ref_dict if k.startswith("ui_"))
                c = sum(cur_dict.get(k, 0) for k in cur_dict if k.startswith("ui_")) if cur_dict else 0
            pct = (100.0 * c / r) if r > 0 else 0
            if r == 0:
                mark = '<span class="cov-na">—</span>'
                detail = "no reference"
            elif c == 0:
                mark = '<span class="cov-bad">✗</span>'
                detail = f"0 / {r}"
            elif c >= r * 0.8:
                mark = '<span class="cov-ok">✓</span>'
                detail = f"{c} / {r} ({pct:.0f}%)"
            else:
                mark = '<span class="cov-bad">✗</span>'
                detail = f"{c} / {r} ({pct:.0f}%)"
            parts.append(
                f'<div class="cov-row"><span class="cov-lbl">{html_module.escape(label)}</span>'
                f'{mark}<code class="cov-path">{html_module.escape(detail)}</code></div>'
            )

        parity_row("HC scene",     "hc_scene",  ref, cur)
        parity_row("UI surfaces",  "_ui_all",   ref, cur)
        parity_row("Voice lines",  "sound",     ref, cur)
        parity_row("Unit models",  "unit",      ref, cur)
        parity_row("Buildings",    "building",  ref, cur)
        parity_row("Resources",    "res_other", ref, cur)

        # Count vanilla parity toward present/missing
        ref_total = ref.get("_total", 0)
        cur_total = cur.get("_total", 0) if cur else 0
        if ref_total > 0:
            if cur_total >= ref_total * 0.8:
                present += 1
            else:
                missing += 1

    summary = (
        f'<div class="cov-summary">{present} present · {missing} missing</div>'
    )
    return summary + "".join(parts), present, missing

# ── Capture thumbnail section renderer ────────────────────────────────────────
def render_captures_section(civ_token, display_name, manifest, ally_manifest):
    """
    Render the "Visual confirmation" section for a civ column.

    manifest      — host-perspective manifest dict (or None)
    ally_manifest — ally-perspective manifest dict (or None)

    Returns an HTML string, or "" if no captures exist for this civ.
    """
    thumbs = []  # list of dicts: {thumb_url, full_url, crop_name, label}
    dir_key = capture_dir_key(civ_token)

    def collect_crops(mf, url_dir_key, is_ally=False):
        """Extract thumbnail entries from a manifest."""
        for capture in mf.get("captures", []):
            for crop in capture.get("crops", []):
                crop_name = crop.get("name", "")
                # For ally, only emit the ally portrait crop
                if is_ally and crop_name != "diplomacy_ally_portrait":
                    continue
                thumb_path = crop.get("thumb_path", "")
                crop_path  = crop.get("crop_path", "")
                if not thumb_path or not crop_path:
                    continue
                # Build URL-relative paths from the deployed base
                # thumb_path is like "thumbs/lobby_portrait.webp"
                # crop_path  is like "crops/lobby_portrait.png"
                thumb_url = f"{VISUAL_ART_URL_BASE}/{url_dir_key}/{thumb_path}"
                full_url  = f"{VISUAL_ART_URL_BASE}/{url_dir_key}/{crop_path}"
                thumbs.append({
                    "thumb_url": thumb_url,
                    "full_url":  full_url,
                    "crop_name": crop_name,
                    "label":     surface_label(crop_name),
                })

    if manifest:
        collect_crops(manifest, dir_key, is_ally=False)

    if ally_manifest:
        # The ally manifest lives under artifacts/validation/visual_art/allies/<dir_key>/
        # and is deployed to artifacts/visual_art/allies/<dir_key>/
        collect_crops(ally_manifest, f"allies/{dir_key}", is_ally=True)

    if not thumbs:
        return ""

    dn_esc = html_module.escape(display_name)
    tok_esc = html_module.escape(civ_token)

    figure_parts = []
    for t in thumbs:
        label_esc      = html_module.escape(t["label"])
        thumb_url_esc  = html_module.escape(t["thumb_url"])
        full_url_esc   = html_module.escape(t["full_url"])
        crop_name_esc  = html_module.escape(t["crop_name"])
        aria            = html_module.escape(f"Open {display_name} {t['label']} full size")
        figure_parts.append(
            f'<figure class="capture-thumb" tabindex="0"'
            f' data-full-src="{full_url_esc}"'
            f' data-civ="{tok_esc}"'
            f' data-surface="{crop_name_esc}"'
            f' aria-label="{aria}">'
            f'<img loading="lazy" src="{thumb_url_esc}" alt="{label_esc}">'
            f'<figcaption>{label_esc}</figcaption>'
            f'</figure>'
        )

    figures_html = "\n      ".join(figure_parts)
    return f"""<div class="captures-section">
  <div class="section-label">Visual confirmation</div>
  <div class="captures-grid">
      {figures_html}
  </div>
</div>
"""


# ── Doctrine evidence renderer (smart walls, elite units, hero+army) ────────
DOCTRINE_SURFACES = [
    ("doctrine_wall_planning",   "Wall planning (T+0:30)"),
    ("doctrine_wall_chokepoint", "Wall chokepoint (T+5:00)"),
    ("doctrine_wall_closure",    "Wall closure (T+10:00)"),
    ("doctrine_elite_units",     "Elite composition (T+15:00)"),
    ("doctrine_hero_attack",     "Hero leading army (T+18:00)"),
    ("doctrine_endgame_state",   "Late-game state (T+22:00)"),
]


def render_doctrine_section(civ_token, display_name):
    """Render doctrine evidence screenshots — embedded directly in the civ column.

    Reads from artifacts/validation/visual_art/<dir_key>/doctrine/<surface>.png
    (full 1920x1080 PNGs).  No manifest required — file existence is the only
    gate.  Captured by tools/aoe3_automation/anw_doctrine_capture_runner.py.

    Returns "" if no doctrine PNGs exist for this civ.
    """
    dir_key = capture_dir_key(civ_token)
    doctrine_dir = os.path.join(VISUAL_ART_DIR, dir_key, "doctrine")
    if not os.path.isdir(doctrine_dir):
        return ""

    figure_parts = []
    for surface_name, label in DOCTRINE_SURFACES:
        png_path = os.path.join(doctrine_dir, f"{surface_name}.png")
        if not os.path.exists(png_path):
            continue
        # URL relative to deployed _site/artifacts/visual_art/<dir_key>/doctrine/
        full_url = f"{VISUAL_ART_URL_BASE}/{dir_key}/doctrine/{surface_name}.png"
        label_esc = html_module.escape(label)
        full_url_esc = html_module.escape(full_url)
        surface_esc = html_module.escape(surface_name)
        tok_esc = html_module.escape(civ_token)
        aria = html_module.escape(f"Open {display_name} {label} doctrine evidence")
        figure_parts.append(
            f'<figure class="doctrine-thumb" tabindex="0"'
            f' data-full-src="{full_url_esc}"'
            f' data-civ="{tok_esc}"'
            f' data-surface="{surface_esc}"'
            f' aria-label="{aria}">'
            f'<img loading="lazy" src="{full_url_esc}" alt="{label_esc}">'
            f'<figcaption>{label_esc}</figcaption>'
            f'</figure>'
        )

    if not figure_parts:
        return ""

    figures_html = "\n      ".join(figure_parts)
    return f"""<div class="doctrine-section">
  <div class="section-label">AI Doctrine Evidence (live game)</div>
  <div class="doctrine-grid">
      {figures_html}
  </div>
</div>
"""


# ── Main column renderer ───────────────────────────────────────────────────────
def render_column(civ_token, civmods, strings, colors, blurbs, spec, decks, cards):
    civ_el = civmods.get(civ_token)
    if civ_el is None:
        return f'<section class="civ-col" id="{html_module.escape(civ_token)}" style="background:#333;color:#fff;"><div class="col-header">{html_module.escape(civ_token)}</div><p>No civmods data</p></section>', 0, 0

    color_entry = colors.get(civ_token, {"r": 60, "g": 60, "b": 80})
    r, g, b = color_entry["r"], color_entry["g"], color_entry["b"]
    tc = text_color(r, g, b)
    bg = bg_style(r, g, b)

    # Display name for header
    display_id = civ_el.findtext("displaynameid") or ""
    display_name = strings.get(display_id, civ_token)

    # Load homecity
    hc_file = civ_el.findtext("homecityfilename") or ""
    hc = load_homecity(hc_file) if hc_file else {}

    # Leader name (for header sub-line)
    leader_name_hdr = ""
    if hc:
        hero_name_raw = hc.get("heroname", "")
        if hero_name_raw.startswith("$$") and hero_name_raw.endswith("$$"):
            loc_id = hero_name_raw[2:-2]
            leader_name_hdr = strings.get(loc_id, hero_name_raw)
        else:
            leader_name_hdr = hero_name_raw
    color_entry2 = colors.get(civ_token, {})
    pc_leader = color_entry2.get("leader", "")
    if not leader_name_hdr and pc_leader:
        leader_name_hdr = pc_leader

    # Doctrine label for header sub-line
    spec_entry, _ = find_spec_entry(civ_token, spec)
    doctrine_label_hdr = spec_entry.get("doctrine_label", "") if spec_entry else ""

    text_html = render_text_section(
        civ_token, civ_el, strings, hc, blurbs, spec, decks, cards, colors
    )
    art_html, resolved, missing = render_art_section(civ_token, civ_el, hc, strings)

    # Load capture manifests (host + ally perspectives)
    host_manifest  = load_capture_manifest(civ_token, ally=False)
    ally_manifest  = load_capture_manifest(civ_token, ally=True)
    captures_html  = render_captures_section(civ_token, display_name, host_manifest, ally_manifest)
    doctrine_html  = render_doctrine_section(civ_token, display_name)

    # Leader image for header (try homecitypreviewwpf)
    leader_preview = civ_el.findtext("homecitypreviewwpf") or ""
    header_img = ""
    if leader_preview:
        tag, ok = img_tag(leader_preview, display_name, 40)
        if ok:
            header_img = tag

    # Sub-line: leader name + doctrine
    sub_parts = []
    if leader_name_hdr:
        sub_parts.append(html_module.escape(leader_name_hdr))
    if doctrine_label_hdr:
        sub_parts.append(f'<span class="hdr-doctrine">{html_module.escape(doctrine_label_hdr)}</span>')
    sub_line = ""
    if sub_parts:
        sub_line = f'<div class="col-sub">{" · ".join(sub_parts)}</div>'

    # ── "Needs full custom art" banner: civ has zero vanilla content AND
    # very little mod-managed content. Pulled from VANILLA_SUMMARY digest.
    summary_stem = vanilla_summary_stem(civ_token)
    van_summary = VANILLA_SUMMARY.get(summary_stem, {}) if VANILLA_SUMMARY else {}
    van_total   = van_summary.get("_total", 0) if van_summary else 0
    empty_banner = ""
    if van_total == 0:
        empty_banner = (
            '<div class="empty-banner">⚠ No vanilla AoE3 DE assets for this civ'
            '<div class="sub">All home-city scene, voice, unit-model, building, '
            'and resource art needs to be custom-authored or aliased to a base civ.</div>'
            '</div>'
        )
    elif van_total < 50:
        empty_banner = (
            f'<div class="empty-banner" style="background:linear-gradient(135deg,rgba(180,130,40,0.92),rgba(140,90,20,0.92));border-color:rgba(255,210,160,0.50);">'
            f'⚠ Minimal vanilla assets ({van_total} entries) — partial coverage only'
            '<div class="sub">Most surfaces will need custom art or a vanilla-civ alias.</div>'
            '</div>'
        )

    col = f"""<section class="civ-col" id="{html_module.escape(civ_token)}" style="{bg}color:{tc}">
  {empty_banner}
  <div class="col-header">
    {header_img}
    <div class="hdr-text">
      <span class="col-name">{html_module.escape(display_name)}</span>
      {sub_line}
    </div>
  </div>
  <div class="col-body">
    {text_html}
    <div class="art-section">
      <div class="section-label">Art &amp; Assets</div>
      {art_html}
      {captures_html}
      {doctrine_html}
    </div>
  </div>
</section>
"""
    return col, resolved, missing

# ── CSS ────────────────────────────────────────────────────────────────────────
CSS = """
* { box-sizing: border-box; margin: 0; padding: 0; }

html, body {
  height: 100%;
  margin: 0;
  overflow: hidden;
  font-family: ui-sans-serif, system-ui, -apple-system, sans-serif;
  font-size: 14px;
  line-height: 1.45;
}

/* One-civ-per-viewport pager: each .civ-col is 100vw × 100vh and
   scroll-snaps to fill the screen. Vertical scroll inside the
   container moves between civs. Internal civ content scrolls
   vertically within its own viewport. */
#scroll-container {
  width: 100vw;
  height: 100vh;
  display: flex;
  flex-direction: column;
  overflow-y: scroll;
  overflow-x: hidden;
  scroll-snap-type: y mandatory;
  scrollbar-width: thin;
  scrollbar-color: rgba(255,255,255,0.45) rgba(0,0,0,0.40);
}
#scroll-container::-webkit-scrollbar {
  width: 14px;
  background: rgba(0,0,0,0.40);
}
#scroll-container::-webkit-scrollbar-thumb {
  background: rgba(255,255,255,0.40);
  border-radius: 7px;
  border: 2px solid rgba(0,0,0,0.40);
}
#scroll-container::-webkit-scrollbar-thumb:hover {
  background: rgba(255,255,255,0.65);
}
#scroll-container::-webkit-scrollbar-track {
  background: rgba(0,0,0,0.30);
}

/* ── Civ page (one per nation, fills viewport) ── */
.civ-col {
  flex: 0 0 100vh;
  width: 100vw;
  height: 100vh;
  scroll-snap-align: start;
  scroll-snap-stop: always;
  overflow: hidden;
  display: flex;
  flex-direction: column;
  border-bottom: 1px solid rgba(0,0,0,0.50);
  position: relative;
}

/* ── Pager controls (fixed in viewport corners) ── */
.pager-toc {
  position: fixed;
  top: 50%;
  right: 12px;
  transform: translateY(-50%);
  z-index: 60;
  background: rgba(0,0,0,0.72);
  border: 1px solid rgba(255,255,255,0.18);
  border-radius: 8px;
  padding: 8px 6px;
  max-height: 90vh;
  overflow-y: auto;
  font-size: 11px;
  color: #eee;
  backdrop-filter: blur(6px);
}
.pager-toc-title {
  font-size: 9.5px;
  font-weight: 800;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  color: rgba(255,255,255,0.65);
  padding: 2px 8px 4px;
  border-bottom: 1px solid rgba(255,255,255,0.14);
  margin-bottom: 4px;
}
.pager-toc a {
  display: block;
  padding: 2px 8px;
  color: rgba(255,255,255,0.78);
  text-decoration: none;
  border-radius: 3px;
  white-space: nowrap;
  transition: background 0.1s, color 0.1s;
  font-size: 10.5px;
}
.pager-toc a:hover {
  background: rgba(255,255,255,0.10);
  color: #fff;
}
.pager-toc a.active {
  background: rgba(255,255,255,0.18);
  color: #fff;
  font-weight: 700;
}

.pager-counter {
  position: fixed;
  top: 12px;
  right: 12px;
  z-index: 60;
  background: rgba(0,0,0,0.72);
  border: 1px solid rgba(255,255,255,0.18);
  border-radius: 6px;
  padding: 4px 10px;
  font-size: 11px;
  font-weight: 700;
  color: #eee;
  letter-spacing: 0.03em;
}

.pager-nav {
  position: fixed;
  bottom: 12px;
  right: 12px;
  z-index: 60;
  display: flex;
  flex-direction: column;
  gap: 4px;
}
.pager-nav button {
  width: 38px;
  height: 38px;
  border-radius: 50%;
  border: 1px solid rgba(255,255,255,0.25);
  background: rgba(0,0,0,0.72);
  color: #fff;
  font-size: 18px;
  font-weight: 700;
  cursor: pointer;
  transition: background 0.1s;
}
.pager-nav button:hover {
  background: rgba(255,255,255,0.18);
}

/* ── Empty civ banner ── */
.empty-banner {
  position: absolute;
  top: 70px;
  left: 50%;
  transform: translateX(-50%);
  z-index: 40;
  background: linear-gradient(135deg, rgba(170,40,40,0.92), rgba(120,20,20,0.92));
  border: 2px solid rgba(255,180,180,0.45);
  border-radius: 8px;
  padding: 14px 24px;
  font-size: 13px;
  font-weight: 700;
  letter-spacing: 0.02em;
  color: #fff;
  text-align: center;
  max-width: 70vw;
  box-shadow: 0 4px 18px rgba(0,0,0,0.45);
  pointer-events: none;
}
.empty-banner .sub {
  font-size: 11px;
  font-weight: 500;
  opacity: 0.85;
  margin-top: 4px;
}

/* ── Header ── */
.col-header {
  display: flex;
  align-items: center;
  gap: 14px;
  padding: 14px 22px;
  background: rgba(0,0,0,0.55);
  border-bottom: 2px solid rgba(255,255,255,0.20);
  flex-shrink: 0;
  min-height: 78px;
}
.col-header img {
  width: 64px; height: 64px;
  object-fit: cover;
  border-radius: 50%;
  border: 3px solid rgba(255,255,255,0.45);
  flex-shrink: 0;
}
.hdr-text {
  display: flex;
  flex-direction: column;
  gap: 2px;
  overflow: hidden;
}
.col-name {
  font-size: 26px;
  font-weight: 800;
  letter-spacing: 0.01em;
  line-height: 1.1;
  color: #fff;
  text-shadow: 0 1px 4px rgba(0,0,0,0.65);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.col-sub {
  font-size: 14px;
  font-weight: 500;
  color: rgba(255,255,255,0.85);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.hdr-doctrine {
  font-style: italic;
  color: rgba(255,220,130,0.92);
}

/* ── Body: text left / art right (side-by-side, internal vertical scroll) ── */
.col-body {
  flex: 1 1 0;
  display: flex;
  flex-direction: row;
  min-height: 0;
  overflow: hidden;
}

/* Left: text/doctrine/cards section */
.text-section {
  flex: 1 1 50%;
  overflow-y: auto;
  overflow-x: hidden;
  padding: 14px 20px;
  background: rgba(0,0,0,0.44);
  border-right: 1px solid rgba(255,255,255,0.12);
  display: flex;
  flex-direction: column;
  gap: 10px;
  scrollbar-width: thin;
  scrollbar-color: rgba(255,255,255,0.35) rgba(0,0,0,0.30);
}
.text-section::-webkit-scrollbar {
  width: 8px;
}
.text-section::-webkit-scrollbar-thumb {
  background: rgba(255,255,255,0.35);
  border-radius: 4px;
}

/* Right: art & assets section */
.art-section {
  flex: 1 1 50%;
  overflow-y: auto;
  overflow-x: hidden;
  padding: 14px 20px;
  background: rgba(0,0,0,0.30);
  display: flex;
  flex-direction: column;
  gap: 6px;
  scrollbar-width: thin;
  scrollbar-color: rgba(255,255,255,0.35) rgba(0,0,0,0.30);
}
.art-section::-webkit-scrollbar {
  width: 8px;
}
.art-section::-webkit-scrollbar-thumb {
  background: rgba(255,255,255,0.35);
  border-radius: 4px;
}

/* ── Info table ── */
.info-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 13px;
}
.info-table tr:hover td {
  background: rgba(255,255,255,0.06);
}
.info-table td {
  padding: 3px 6px;
  vertical-align: top;
}
.info-table .lbl {
  width: 32%;
  color: rgba(255,255,255,0.66);
  font-weight: 600;
  white-space: nowrap;
  font-size: 12px;
  padding-right: 8px;
}
.info-table .mono code {
  font-family: ui-monospace, 'Cascadia Code', Menlo, monospace;
  font-size: 12px;
  background: rgba(0,0,0,0.35);
  padding: 1px 5px;
  border-radius: 3px;
}
.info-table .blurb-cell {
  font-size: 13px;
  line-height: 1.45;
  color: rgba(255,255,255,0.90);
}

/* ── Cards section ── */
.cards-section {
  flex: 0 0 auto;
  font-size: 13px;
  line-height: 1.4;
}
.age-row {
  margin-bottom: 3px;
  display: flex;
  align-items: flex-start;
  gap: 4px;
  padding: 2px 3px;
  border-radius: 3px;
  overflow: hidden;
}
/* Age-band colour coding */
.age-row.age-0 { background: rgba(130,130,130,0.22); }  /* Discovery — gray  */
.age-row.age-1 { background: rgba(160,130, 70,0.22); }  /* Colonial  — tan   */
.age-row.age-2 { background: rgba( 60,100,180,0.25); }  /* Fortress  — blue  */
.age-row.age-3 { background: rgba(180,130, 20,0.25); }  /* Industrial— amber */
.age-row.age-4 { background: rgba(160, 40, 40,0.25); }  /* Imperial  — red   */

.age-lbl {
  display: inline-block;
  font-weight: 700;
  font-size: 11px;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  opacity: 0.92;
  padding: 2px 6px;
  border-radius: 3px;
  flex-shrink: 0;
  align-self: center;
  min-width: 72px;
}
/* Stronger pill colours for the label itself */
.age-row.age-0 .age-lbl { background: rgba(160,160,160,0.35); }
.age-row.age-1 .age-lbl { background: rgba(180,145, 80,0.40); }
.age-row.age-2 .age-lbl { background: rgba( 80,130,210,0.40); }
.age-row.age-3 .age-lbl { background: rgba(200,155, 30,0.40); }
.age-row.age-4 .age-lbl { background: rgba(190, 55, 55,0.40); }

.age-row:hover {
  background: rgba(255,255,255,0.10) !important;
}

/* Card thumbnails inside an age-row */
.age-cards {
  display: inline-flex;
  flex-wrap: wrap;
  gap: 2px;
  vertical-align: middle;
}
.card-img {
  width: 36px;
  height: 36px;
  object-fit: contain;
  border: 1px solid rgba(255,255,255,0.18);
  border-radius: 3px;
  background: rgba(0,0,0,0.30);
  cursor: help;
  transition: transform 0.12s, border-color 0.12s, box-shadow 0.12s;
}
.card-img:hover {
  transform: scale(1.8);
  border-color: rgba(255,255,255,0.65);
  box-shadow: 0 0 6px rgba(0,0,0,0.55);
  z-index: 2;
  position: relative;
}
.card-text {
  display: inline-block;
  font-size: 8.5px;
  padding: 0 3px;
  border-radius: 2px;
  background: rgba(255,255,255,0.08);
  color: rgba(255,255,255,0.80);
  cursor: help;
}

/* ── Art rows ── */
.art-row {
  display: flex;
  align-items: flex-start;
  gap: 8px;
  margin-bottom: 5px;
}
.art-lbl {
  font-size: 11px;
  font-weight: 600;
  color: rgba(255,255,255,0.65);
  min-width: 100px;
  max-width: 120px;
  flex-shrink: 0;
  padding-top: 4px;
  line-height: 1.3;
}
.art-row img {
  width: 84px;
  height: 84px;
  object-fit: contain;
  border: 1px solid rgba(255,255,255,0.22);
  border-radius: 4px;
  background: rgba(0,0,0,0.30);
  flex-shrink: 0;
  transition: box-shadow 0.15s, border-color 0.15s;
}
.art-row img:hover {
  border-color: rgba(255,255,255,0.55);
  box-shadow: 0 0 6px rgba(255,255,255,0.25);
}

/* Engine-path text: monospace, truncated, full path on hover title */
.path-text {
  font-family: ui-monospace, 'Cascadia Code', Menlo, monospace;
  font-size: 11px;
  color: rgba(255,255,255,0.74);
  background: rgba(0,0,0,0.30);
  padding: 2px 5px;
  border-radius: 3px;
  display: block;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  max-width: 100%;
  line-height: 1.4;
  cursor: default;
}
.path-missing code {
  font-family: ui-monospace, 'Cascadia Code', Menlo, monospace;
  font-size: 11px;
  color: rgba(255,120,120,0.78);
  word-break: break-all;
}

/* ── Art coverage audit ── */
.cov-summary {
  font-size: 13px;
  font-weight: 700;
  color: rgba(255,255,255,0.78);
  margin-bottom: 8px;
  padding: 6px 10px;
  background: rgba(0,0,0,0.30);
  border-radius: 4px;
}
.cov-group-lbl {
  font-size: 11px;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  color: rgba(255,255,255,0.55);
  margin: 12px 0 4px;
  border-bottom: 1px dotted rgba(255,255,255,0.15);
  padding-bottom: 2px;
}
.cov-row {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 3px;
  font-size: 12px;
  line-height: 1.35;
}
.cov-lbl {
  font-size: 12px;
  font-weight: 600;
  color: rgba(255,255,255,0.70);
  min-width: 150px;
  max-width: 180px;
  flex-shrink: 0;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.cov-ok {
  color: #6ee07a;
  font-weight: 700;
  font-size: 14px;
  flex-shrink: 0;
}
.cov-bad {
  color: #ff7777;
  font-weight: 700;
  font-size: 14px;
  flex-shrink: 0;
}
.cov-na {
  color: rgba(255,255,255,0.35);
  font-weight: 700;
  font-size: 14px;
  flex-shrink: 0;
}
.cov-thumb {
  width: 40px;
  height: 40px;
  object-fit: contain;
  border: 1px solid rgba(255,255,255,0.22);
  border-radius: 3px;
  background: rgba(0,0,0,0.30);
  flex-shrink: 0;
  cursor: help;
  transition: transform 0.12s, border-color 0.12s, box-shadow 0.12s;
}
.cov-thumb:hover {
  transform: scale(3.0);
  border-color: rgba(255,255,255,0.65);
  box-shadow: 0 0 10px rgba(0,0,0,0.65);
  z-index: 30;
  position: relative;
}
.cov-path {
  font-family: ui-monospace, 'Cascadia Code', Menlo, monospace;
  font-size: 11px;
  color: rgba(255,255,255,0.60);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  min-width: 0;
  flex-shrink: 1;
}
.cov-path.cov-path-missing {
  color: rgba(255,120,120,0.75);
}
.cov-leader .cov-lbl {
  padding-left: 12px;
  color: rgba(255,255,255,0.78);
}

.section-label {
  font-size: 12px;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  color: rgba(255,255,255,0.62);
  margin: 4px 0 6px;
  flex-shrink: 0;
  border-bottom: 1px solid rgba(255,255,255,0.14);
  padding-bottom: 3px;
}

.empty { opacity: 0.38; font-style: italic; }

/* ── Visual capture thumbnails ── */
.captures-section {
  flex-shrink: 0;
  margin-top: 4px;
  padding-top: 3px;
  border-top: 1px solid rgba(255,255,255,0.10);
}

/* 4 or 5 column grid — thumbs are 56-72px tall; 2 rows of 5 fit without overflow */
.captures-grid {
  display: grid;
  grid-template-columns: repeat(5, 1fr);
  gap: 3px;
  /* No overflow here — constraint is honoured by column height */
}

.capture-thumb {
  cursor: pointer;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  align-items: center;
  border-radius: 3px;
  border: 1px solid rgba(255,255,255,0.18);
  background: rgba(0,0,0,0.30);
  overflow: hidden;
  transition: transform 0.12s ease, box-shadow 0.12s ease, filter 0.12s ease;
  box-shadow: 0 1px 3px rgba(0,0,0,0.45);
  outline: none;
}

.capture-thumb:hover {
  transform: scale(1.04);
  filter: brightness(1.1);
  box-shadow: 0 2px 8px rgba(0,0,0,0.65);
  border-color: rgba(255,255,255,0.50);
}

.capture-thumb:focus-visible {
  outline: 2px solid rgba(100,180,255,0.85);
  outline-offset: 1px;
}

.capture-thumb img {
  width: 100%;
  height: 56px;
  object-fit: cover;
  display: block;
}

.capture-thumb figcaption {
  font-size: 7px;
  font-weight: 600;
  text-align: center;
  color: rgba(255,255,255,0.72);
  padding: 1px 2px 2px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  max-width: 100%;
  line-height: 1.2;
}

/* ── Doctrine evidence section (AI live-game proofs) ── */
.doctrine-section {
  flex-shrink: 0;
  margin-top: 4px;
  padding-top: 3px;
  border-top: 1px solid rgba(255,220,140,0.22);
}

.doctrine-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 3px;
}

.doctrine-thumb {
  cursor: pointer;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  align-items: center;
  border-radius: 3px;
  border: 1px solid rgba(255,220,140,0.32);
  background: rgba(60,40,10,0.40);
  transition: transform 80ms ease, box-shadow 80ms ease;
}

.doctrine-thumb:hover {
  transform: scale(1.05);
  box-shadow: 0 2px 8px rgba(0,0,0,0.65);
  border-color: rgba(255,220,140,0.85);
}

.doctrine-thumb:focus-visible {
  outline: 2px solid rgba(255,220,140,0.85);
  outline-offset: 1px;
}

.doctrine-thumb img {
  width: 100%;
  height: 64px;
  object-fit: cover;
  display: block;
}

.doctrine-thumb figcaption {
  font-size: 7px;
  font-weight: 600;
  text-align: center;
  color: rgba(255,220,140,0.88);
  padding: 1px 2px 2px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  max-width: 100%;
  line-height: 1.2;
}

/* ── Lightbox modal ── */
.capture-modal {
  position: fixed;
  inset: 0;
  z-index: 9000;
  background: rgba(0,0,0,0.92);
  display: flex;
  align-items: center;
  justify-content: center;
  /* No overflow rules here — intentional, to avoid conflicting with
     the no-vertical-scroll constraint on the column layout */
}

/* When hidden attribute is present the browser hides it — no extra CSS needed */
.capture-modal[hidden] {
  display: none;
}

.modal-close {
  position: absolute;
  top: 14px;
  right: 18px;
  background: rgba(255,255,255,0.10);
  border: 1px solid rgba(255,255,255,0.25);
  color: #fff;
  font-size: 22px;
  line-height: 1;
  width: 36px;
  height: 36px;
  border-radius: 50%;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: background 0.15s;
  z-index: 9001;
}

.modal-close:hover {
  background: rgba(255,255,255,0.22);
}

.modal-content {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 10px;
  max-width: 95vw;
  max-height: 90vh;
}

#modal-img {
  max-width: 95vw;
  max-height: 83vh;
  object-fit: contain;
  border-radius: 4px;
  box-shadow: 0 4px 32px rgba(0,0,0,0.8);
  display: block;
}

#modal-caption {
  color: rgba(255,255,255,0.82);
  font-size: 13px;
  font-weight: 500;
  letter-spacing: 0.02em;
  text-align: center;
  text-shadow: 0 1px 3px rgba(0,0,0,0.6);
}
"""

# ── Lightbox JS (vanilla, no framework) ───────────────────────────────────────
# Uses __CIV_DISPLAY_MAP__ as a substitution token — replaced at build time
# via str.replace() to avoid Python format() conflicts with JS braces.
LIGHTBOX_JS = r"""
(function () {
  'use strict';

  // Map from civ_token -> human display name, injected by the generator
  var CIV_DISPLAY = __CIV_DISPLAY_MAP__;

  // Surface labels matching CROP_SURFACE_LABELS in the Python generator
  var SURFACE_LABELS = {
    lobby_portrait:          'Lobby portrait',
    loading_flag:            'Loading flag',
    home_city_button:        'Home City button',
    hud_flag_corner:         'HUD flag corner',
    home_city_scene:         'Home City scene',
    tech_tree_overview:      'Tech tree overview',
    diplomacy_panel:         'Diplomacy panel',
    scoreboard_player_row:   'Scoreboard row',
    esc_menu_player_summary: 'ESC menu summary',
    endgame_flag:            'Endgame flag',
    diplomacy_ally_portrait: 'Ally portrait'
  };

  function surfaceLabel(name) {
    return SURFACE_LABELS[name] || name.replace(/_/g, ' ').replace(/\b\w/g, function(c){ return c.toUpperCase(); });
  }

  var modal    = document.getElementById('capture-modal');
  var modalImg = document.getElementById('modal-img');
  var caption  = document.getElementById('modal-caption');

  function openModal(figure) {
    var fullSrc  = figure.dataset.fullSrc;
    var civToken = figure.dataset.civ;
    var surface  = figure.dataset.surface;
    var civName  = CIV_DISPLAY[civToken] || civToken;
    modalImg.src = fullSrc;
    modalImg.alt = civName + ' \u2014 ' + surfaceLabel(surface);
    caption.textContent = civName + ' \u2014 ' + surfaceLabel(surface);
    modal.removeAttribute('hidden');
    modal.focus();
  }

  function closeModal() {
    modal.setAttribute('hidden', '');
    modalImg.src = '';  // free memory
  }

  function getAllThumbs(figure) {
    var col = figure.closest('.civ-col');
    if (!col) return [];
    return Array.from(col.querySelectorAll('.capture-thumb, .doctrine-thumb'));
  }

  // Track the currently open figure for arrow navigation
  var currentFigure = null;

  // Event delegation — click on any .capture-thumb
  document.addEventListener('click', function (e) {
    var fig = e.target.closest('.capture-thumb, .doctrine-thumb');
    if (fig) {
      currentFigure = fig;
      openModal(fig);
      return;
    }
    // Close on backdrop click (not on image or caption)
    if (e.target === modal) {
      closeModal();
      currentFigure = null;
    }
  });

  function navigateAndTrack(direction) {
    if (!currentFigure) return;
    var thumbs = getAllThumbs(currentFigure);
    if (thumbs.length === 0) return;
    var idx  = thumbs.indexOf(currentFigure);
    var next = (idx + direction + thumbs.length) % thumbs.length;
    currentFigure = thumbs[next];
    openModal(currentFigure);
  }

  // Keyboard handler
  document.addEventListener('keydown', function (e) {
    if (modal.hasAttribute('hidden')) return;
    if (e.key === 'Escape') {
      closeModal();
      currentFigure = null;
    } else if (e.key === 'ArrowLeft') {
      navigateAndTrack(-1);
    } else if (e.key === 'ArrowRight') {
      navigateAndTrack(1);
    }
  });

  // Close button
  document.querySelector('.modal-close').addEventListener('click', function () {
    closeModal();
    currentFigure = null;
  });

  // Keyboard activation on thumbnails (Enter / Space)
  document.addEventListener('keydown', function (e) {
    if (e.key !== 'Enter' && e.key !== ' ') return;
    var fig = document.activeElement && document.activeElement.closest('.capture-thumb, .doctrine-thumb');
    if (fig) {
      e.preventDefault();
      currentFigure = fig;
      openModal(fig);
    }
  });

  // Pre-cache on hover (pointer: fine devices only)
  var supportsPointerFine = window.matchMedia && window.matchMedia('(pointer: fine)').matches;
  if (supportsPointerFine) {
    document.addEventListener('mouseover', function (e) {
      var fig = e.target.closest('.capture-thumb, .doctrine-thumb');
      if (fig && fig.dataset.fullSrc && !fig._precached) {
        fig._precached = true;
        var img = new Image();
        img.src = fig.dataset.fullSrc;
      }
    });
  }

  // Vertical pager: one civ per 100vh page, scroll-snap-y mandatory.
  // We override mouse-wheel to snap-to-next/prev section instead of free-scroll.
  var scroller = document.getElementById('scroll-container');
  var sections = Array.prototype.slice.call(document.querySelectorAll('.civ-col'));
  var counter  = document.getElementById('pager-counter');
  var tocEl    = document.getElementById('pager-toc');

  function currentIndex() {
    if (!scroller) return 0;
    return Math.round(scroller.scrollTop / window.innerHeight);
  }

  function gotoIndex(idx) {
    if (!scroller) return;
    idx = Math.max(0, Math.min(sections.length - 1, idx));
    scroller.scrollTo({ top: idx * window.innerHeight, behavior: 'smooth' });
    updateActive(idx);
    if (sections[idx] && sections[idx].id) {
      history.replaceState(null, '', '#' + sections[idx].id);
    }
  }

  function updateActive(idx) {
    if (counter) {
      counter.textContent = (idx + 1) + ' / ' + sections.length;
    }
    if (tocEl) {
      var links = tocEl.querySelectorAll('a');
      for (var i = 0; i < links.length; i++) {
        links[i].classList.toggle('active', i === idx);
      }
      // Scroll active item into view in the ToC
      var active = links[idx];
      if (active) {
        active.scrollIntoView({ block: 'nearest', behavior: 'smooth' });
      }
    }
  }

  // Wheel: snap one section at a time. Debounce so a single wheel-roll
  // doesn't skip multiple civs.
  var wheelLock = false;
  window.addEventListener('wheel', function (e) {
    if (!scroller) return;
    var modal = document.getElementById('capture-modal');
    if (modal && !modal.hidden) return;
    // Allow internal scroll inside the text/art sections — only intercept
    // when the wheel target is the page background (not within a scrollable child).
    var target = e.target;
    while (target && target !== scroller && target !== document.body) {
      var style = window.getComputedStyle(target);
      if ((style.overflowY === 'auto' || style.overflowY === 'scroll')
          && target.scrollHeight > target.clientHeight) {
        // Inside a scrollable child — let it scroll normally.
        return;
      }
      target = target.parentElement;
    }
    if (Math.abs(e.deltaY) < 5) return;
    if (wheelLock) { e.preventDefault(); return; }
    e.preventDefault();
    wheelLock = true;
    var dir = e.deltaY > 0 ? 1 : -1;
    gotoIndex(currentIndex() + dir);
    setTimeout(function () { wheelLock = false; }, 380);
  }, { passive: false });

  // Keyboard: Down/Right/PageDown/Space = next; Up/Left/PageUp = prev;
  // Home/End = first/last; digits 1-9 = nth civ (1-indexed).
  document.addEventListener('keydown', function (e) {
    if (!scroller) return;
    var modal = document.getElementById('capture-modal');
    if (modal && !modal.hidden) return;
    if (e.key === 'ArrowDown' || e.key === 'ArrowRight' || e.key === 'PageDown' || e.key === ' ') {
      e.preventDefault(); gotoIndex(currentIndex() + 1);
    } else if (e.key === 'ArrowUp' || e.key === 'ArrowLeft' || e.key === 'PageUp') {
      e.preventDefault(); gotoIndex(currentIndex() - 1);
    } else if (e.key === 'Home') {
      e.preventDefault(); gotoIndex(0);
    } else if (e.key === 'End') {
      e.preventDefault(); gotoIndex(sections.length - 1);
    } else if (/^[1-9]$/.test(e.key)) {
      e.preventDefault(); gotoIndex(parseInt(e.key, 10) - 1);
    }
  });

  // Pager nav buttons (▲ / ▼) — use onclick wired via id.
  var btnPrev = document.getElementById('pager-prev');
  var btnNext = document.getElementById('pager-next');
  if (btnPrev) btnPrev.addEventListener('click', function () { gotoIndex(currentIndex() - 1); });
  if (btnNext) btnNext.addEventListener('click', function () { gotoIndex(currentIndex() + 1); });

  // ToC link clicks
  if (tocEl) {
    tocEl.addEventListener('click', function (e) {
      var a = e.target.closest('a[data-idx]');
      if (!a) return;
      e.preventDefault();
      gotoIndex(parseInt(a.dataset.idx, 10));
    });
  }

  // Track scroll to update counter/ToC highlight.
  var scrollTimer = null;
  scroller.addEventListener('scroll', function () {
    if (scrollTimer) return;
    scrollTimer = setTimeout(function () {
      updateActive(currentIndex());
      scrollTimer = null;
    }, 80);
  });

  // Open at hash if present (e.g. #ANWCanadians).
  if (location.hash) {
    var target = document.getElementById(location.hash.slice(1));
    if (target) {
      var idx = sections.indexOf(target);
      if (idx >= 0) {
        // jump (no smooth) on initial load
        scroller.scrollTop = idx * window.innerHeight;
        updateActive(idx);
        return;
      }
    }
  }
  updateActive(0);
}());
"""

# ── CIV display name map builder ──────────────────────────────────────────────
def build_civ_display_map(civ_order, civmods, strings):
    """Return a JS object literal mapping civ_token -> display name."""
    pairs = []
    for token in civ_order:
        civ_el = civmods.get(token)
        if civ_el is not None:
            display_id   = civ_el.findtext("displaynameid") or ""
            display_name = strings.get(display_id, token)
        else:
            display_name = token
        # Escape for JS string literal
        safe_token = token.replace("'", "\\'")
        safe_name  = display_name.replace("'", "\\'")
        pairs.append(f"  '{safe_token}': '{safe_name}'")
    return "{\n" + ",\n".join(pairs) + "\n}"


# ── CIV order (same as playercolors.xml, which has 45 entries) ────────────────
def get_civ_order():
    path = os.path.join(DATA_DIR, "playercolors.xml")
    tree = ET.parse(path)
    return [c.get("civ") for c in tree.getroot().findall(".//Color") if c.get("civ")]

# ── Build ──────────────────────────────────────────────────────────────────────
def build():
    print("Loading data sources...")
    strings = load_strings()
    civmods = load_civmods()
    colors  = load_playercolors()
    blurbs  = load_blurbs()
    spec    = load_playstyle_spec()
    decks   = load_decks()
    cards   = load_cards()

    civ_order = get_civ_order()
    print(f"Building {len(civ_order)} columns...")

    columns_html = []
    total_resolved = 0
    total_missing  = 0

    for civ_token in civ_order:
        col_html, resolved, missing = render_column(
            civ_token, civmods, strings, colors, blurbs, spec, decks, cards
        )
        columns_html.append(col_html)
        total_resolved += resolved
        total_missing  += missing

    num_cols = len(civ_order)

    # Build a JS mapping from civ_token -> display_name for modal captions
    civ_display_map_js = build_civ_display_map(civ_order, civmods, strings)

    lightbox_js = LIGHTBOX_JS.replace("__CIV_DISPLAY_MAP__", civ_display_map_js)

    # Build ToC (table-of-contents) sidebar: one link per civ, with display name.
    toc_items = []
    for idx, token in enumerate(civ_order):
        civ_el = civmods.get(token)
        if civ_el is not None:
            display_id   = civ_el.findtext("displaynameid") or ""
            display_name = strings.get(display_id, token)
        else:
            display_name = token
        # Mark civs with empty vanilla parity using a small dot
        van_total = VANILLA_SUMMARY.get(vanilla_summary_stem(token), {}).get("_total", 0) if VANILLA_SUMMARY else 0
        marker = ""
        if van_total == 0:
            marker = ' <span style="color:#ff8a8a;">●</span>'
        elif van_total < 50:
            marker = ' <span style="color:#ffc070;">●</span>'
        toc_items.append(
            f'<a href="#{html_module.escape(token)}" data-idx="{idx}" title="{html_module.escape(token)}">'
            f'{html_module.escape(display_name)}{marker}</a>'
        )
    toc_html = (
        '<nav id="pager-toc" class="pager-toc" aria-label="Civ navigation">'
        f'<div class="pager-toc-title">{num_cols} nations</div>'
        + "".join(toc_items)
        + '</nav>'
    )

    html_out = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ANW Civ Review — A New World ({num_cols} nations)</title>
<style>
{CSS}
</style>
</head>
<body>
<!-- {num_cols} civs · vertical pager, one civ per 100vh page (scroll-snap-y mandatory) -->
<div id="pager-counter" class="pager-counter">1 / {num_cols}</div>
{toc_html}
<div class="pager-nav">
  <button id="pager-prev" aria-label="Previous nation (↑)">▲</button>
  <button id="pager-next" aria-label="Next nation (↓)">▼</button>
</div>
<div id="scroll-container">
{"".join(columns_html)}
</div>
<!-- Shared lightbox modal — one instance for the entire page -->
<div id="capture-modal" class="capture-modal" hidden>
  <button class="modal-close" aria-label="Close (Esc)">&times;</button>
  <div class="modal-content">
    <img id="modal-img" src="" alt="">
    <div id="modal-caption"></div>
  </div>
</div>
<script>
{lightbox_js}
</script>
</body>
</html>
"""

    with open(OUTPUT_HTML, "w", encoding="utf-8") as f:
        f.write(html_out)

    print(f"Written: {OUTPUT_HTML}")
    print(f"Columns: {num_cols}")
    print(f"Art assets resolved as <img>: {total_resolved}")
    print(f"Art assets skipped (path missing): {total_missing}")
    print(f"File size: {os.path.getsize(OUTPUT_HTML):,} bytes")

if __name__ == "__main__":
    build()
